# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainWindow.ui'
#
# Created: Mon Feb 18 10:29:43 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1096, 879)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabWidget_database = QtGui.QTabWidget(self.groupBox_5)
        self.tabWidget_database.setObjectName(_fromUtf8("tabWidget_database"))
        self.tab_database_1 = QtGui.QWidget()
        self.tab_database_1.setObjectName(_fromUtf8("tab_database_1"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.tab_database_1)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.tableWidget_database1 = QtGui.QTableWidget(self.tab_database_1)
        self.tableWidget_database1.setObjectName(_fromUtf8("tableWidget_database1"))
        self.tableWidget_database1.setColumnCount(11)
        self.tableWidget_database1.setRowCount(11)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database1.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database1.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database1.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database1.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database1.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database1.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database1.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database1.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database1.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database1.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database1.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database1.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database1.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database1.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database1.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database1.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database1.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database1.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database1.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database1.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database1.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database1.setHorizontalHeaderItem(10, item)
        self.verticalLayout_24.addWidget(self.tableWidget_database1)
        self.horizontalLayout_12.addLayout(self.verticalLayout_24)
        self.tabWidget_database.addTab(self.tab_database_1, _fromUtf8(""))
        self.tab_database_2 = QtGui.QWidget()
        self.tab_database_2.setObjectName(_fromUtf8("tab_database_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab_database_2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tableWidget_database2 = QtGui.QTableWidget(self.tab_database_2)
        self.tableWidget_database2.setObjectName(_fromUtf8("tableWidget_database2"))
        self.tableWidget_database2.setColumnCount(11)
        self.tableWidget_database2.setRowCount(11)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database2.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database2.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database2.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database2.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database2.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database2.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database2.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database2.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database2.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database2.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database2.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database2.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database2.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database2.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database2.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database2.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database2.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database2.setHorizontalHeaderItem(10, item)
        self.verticalLayout_5.addWidget(self.tableWidget_database2)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.tabWidget_database.addTab(self.tab_database_2, _fromUtf8(""))
        self.tab_database_3 = QtGui.QWidget()
        self.tab_database_3.setObjectName(_fromUtf8("tab_database_3"))
        self.verticalLayout_28 = QtGui.QVBoxLayout(self.tab_database_3)
        self.verticalLayout_28.setMargin(0)
        self.verticalLayout_28.setObjectName(_fromUtf8("verticalLayout_28"))
        self.verticalLayout_27 = QtGui.QVBoxLayout()
        self.verticalLayout_27.setObjectName(_fromUtf8("verticalLayout_27"))
        self.tableWidget_database3 = QtGui.QTableWidget(self.tab_database_3)
        self.tableWidget_database3.setObjectName(_fromUtf8("tableWidget_database3"))
        self.tableWidget_database3.setColumnCount(11)
        self.tableWidget_database3.setRowCount(11)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database3.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database3.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database3.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database3.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database3.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database3.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database3.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database3.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database3.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database3.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database3.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database3.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database3.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database3.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database3.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database3.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database3.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database3.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database3.setHorizontalHeaderItem(10, item)
        self.verticalLayout_27.addWidget(self.tableWidget_database3)
        self.verticalLayout_28.addLayout(self.verticalLayout_27)
        self.tabWidget_database.addTab(self.tab_database_3, _fromUtf8(""))
        self.tab_database_4 = QtGui.QWidget()
        self.tab_database_4.setObjectName(_fromUtf8("tab_database_4"))
        self.verticalLayout_30 = QtGui.QVBoxLayout(self.tab_database_4)
        self.verticalLayout_30.setMargin(0)
        self.verticalLayout_30.setObjectName(_fromUtf8("verticalLayout_30"))
        self.verticalLayout_29 = QtGui.QVBoxLayout()
        self.verticalLayout_29.setObjectName(_fromUtf8("verticalLayout_29"))
        self.tableWidget_database4 = QtGui.QTableWidget(self.tab_database_4)
        self.tableWidget_database4.setObjectName(_fromUtf8("tableWidget_database4"))
        self.tableWidget_database4.setColumnCount(11)
        self.tableWidget_database4.setRowCount(11)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database4.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database4.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database4.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database4.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database4.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database4.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database4.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database4.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database4.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database4.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database4.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database4.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database4.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database4.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database4.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database4.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database4.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database4.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database4.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database4.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database4.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database4.setHorizontalHeaderItem(10, item)
        self.verticalLayout_29.addWidget(self.tableWidget_database4)
        self.verticalLayout_30.addLayout(self.verticalLayout_29)
        self.tabWidget_database.addTab(self.tab_database_4, _fromUtf8(""))
        self.tab_database_5 = QtGui.QWidget()
        self.tab_database_5.setObjectName(_fromUtf8("tab_database_5"))
        self.verticalLayout_32 = QtGui.QVBoxLayout(self.tab_database_5)
        self.verticalLayout_32.setMargin(0)
        self.verticalLayout_32.setObjectName(_fromUtf8("verticalLayout_32"))
        self.verticalLayout_31 = QtGui.QVBoxLayout()
        self.verticalLayout_31.setObjectName(_fromUtf8("verticalLayout_31"))
        self.tableWidget_database5 = QtGui.QTableWidget(self.tab_database_5)
        self.tableWidget_database5.setObjectName(_fromUtf8("tableWidget_database5"))
        self.tableWidget_database5.setColumnCount(11)
        self.tableWidget_database5.setRowCount(11)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database5.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database5.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database5.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database5.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database5.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database5.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database5.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database5.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database5.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database5.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database5.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database5.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database5.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database5.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database5.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database5.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database5.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database5.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database5.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database5.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database5.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database5.setHorizontalHeaderItem(10, item)
        self.verticalLayout_31.addWidget(self.tableWidget_database5)
        self.verticalLayout_32.addLayout(self.verticalLayout_31)
        self.tabWidget_database.addTab(self.tab_database_5, _fromUtf8(""))
        self.tab_database_6 = QtGui.QWidget()
        self.tab_database_6.setObjectName(_fromUtf8("tab_database_6"))
        self.verticalLayout_34 = QtGui.QVBoxLayout(self.tab_database_6)
        self.verticalLayout_34.setMargin(0)
        self.verticalLayout_34.setObjectName(_fromUtf8("verticalLayout_34"))
        self.verticalLayout_33 = QtGui.QVBoxLayout()
        self.verticalLayout_33.setObjectName(_fromUtf8("verticalLayout_33"))
        self.tableWidget_database6 = QtGui.QTableWidget(self.tab_database_6)
        self.tableWidget_database6.setObjectName(_fromUtf8("tableWidget_database6"))
        self.tableWidget_database6.setColumnCount(11)
        self.tableWidget_database6.setRowCount(11)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database6.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database6.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database6.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database6.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database6.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database6.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database6.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database6.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database6.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database6.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database6.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database6.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database6.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database6.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database6.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database6.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database6.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database6.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database6.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database6.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database6.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_database6.setHorizontalHeaderItem(10, item)
        self.verticalLayout_33.addWidget(self.tableWidget_database6)
        self.verticalLayout_34.addLayout(self.verticalLayout_33)
        self.tabWidget_database.addTab(self.tab_database_6, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidget_database)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.tabWidget_script = QtGui.QTabWidget(self.groupBox_4)
        self.tabWidget_script.setObjectName(_fromUtf8("tabWidget_script"))
        self.tab_script_1 = QtGui.QWidget()
        self.tab_script_1.setObjectName(_fromUtf8("tab_script_1"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab_script_1)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.tableWidget_script_1 = QtGui.QTableWidget(self.tab_script_1)
        self.tableWidget_script_1.setObjectName(_fromUtf8("tableWidget_script_1"))
        self.tableWidget_script_1.setColumnCount(16)
        self.tableWidget_script_1.setRowCount(11)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_1.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_1.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_1.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_1.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_1.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_1.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_1.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_1.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_1.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_1.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_1.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_1.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_1.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_1.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_1.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_1.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_1.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_1.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_1.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_1.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_1.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_1.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_1.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_1.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_1.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_1.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_1.setHorizontalHeaderItem(15, item)
        self.verticalLayout_8.addWidget(self.tableWidget_script_1)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.tabWidget_script.addTab(self.tab_script_1, _fromUtf8(""))
        self.tab_script_2 = QtGui.QWidget()
        self.tab_script_2.setObjectName(_fromUtf8("tab_script_2"))
        self.verticalLayout_36 = QtGui.QVBoxLayout(self.tab_script_2)
        self.verticalLayout_36.setMargin(0)
        self.verticalLayout_36.setObjectName(_fromUtf8("verticalLayout_36"))
        self.verticalLayout_35 = QtGui.QVBoxLayout()
        self.verticalLayout_35.setObjectName(_fromUtf8("verticalLayout_35"))
        self.tableWidget_script_2 = QtGui.QTableWidget(self.tab_script_2)
        self.tableWidget_script_2.setObjectName(_fromUtf8("tableWidget_script_2"))
        self.tableWidget_script_2.setColumnCount(16)
        self.tableWidget_script_2.setRowCount(11)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_2.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_2.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_2.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_2.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_2.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_2.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_2.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_2.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_2.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_2.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_2.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_2.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_2.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_2.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_2.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_2.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_2.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_2.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_2.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_2.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_2.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_2.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_2.setHorizontalHeaderItem(15, item)
        self.verticalLayout_35.addWidget(self.tableWidget_script_2)
        self.verticalLayout_36.addLayout(self.verticalLayout_35)
        self.tabWidget_script.addTab(self.tab_script_2, _fromUtf8(""))
        self.tab_script_3 = QtGui.QWidget()
        self.tab_script_3.setObjectName(_fromUtf8("tab_script_3"))
        self.verticalLayout_38 = QtGui.QVBoxLayout(self.tab_script_3)
        self.verticalLayout_38.setMargin(0)
        self.verticalLayout_38.setObjectName(_fromUtf8("verticalLayout_38"))
        self.verticalLayout_37 = QtGui.QVBoxLayout()
        self.verticalLayout_37.setObjectName(_fromUtf8("verticalLayout_37"))
        self.tableWidget_script_3 = QtGui.QTableWidget(self.tab_script_3)
        self.tableWidget_script_3.setObjectName(_fromUtf8("tableWidget_script_3"))
        self.tableWidget_script_3.setColumnCount(16)
        self.tableWidget_script_3.setRowCount(11)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_3.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_3.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_3.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_3.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_3.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_3.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_3.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_3.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_3.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_3.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_3.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_3.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_3.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_3.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_3.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_3.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_3.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_3.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_3.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_3.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_3.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_3.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_3.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_3.setHorizontalHeaderItem(15, item)
        self.verticalLayout_37.addWidget(self.tableWidget_script_3)
        self.verticalLayout_38.addLayout(self.verticalLayout_37)
        self.tabWidget_script.addTab(self.tab_script_3, _fromUtf8(""))
        self.tab_script_4 = QtGui.QWidget()
        self.tab_script_4.setObjectName(_fromUtf8("tab_script_4"))
        self.verticalLayout_40 = QtGui.QVBoxLayout(self.tab_script_4)
        self.verticalLayout_40.setMargin(0)
        self.verticalLayout_40.setObjectName(_fromUtf8("verticalLayout_40"))
        self.verticalLayout_39 = QtGui.QVBoxLayout()
        self.verticalLayout_39.setObjectName(_fromUtf8("verticalLayout_39"))
        self.tableWidget_script_4 = QtGui.QTableWidget(self.tab_script_4)
        self.tableWidget_script_4.setObjectName(_fromUtf8("tableWidget_script_4"))
        self.tableWidget_script_4.setColumnCount(16)
        self.tableWidget_script_4.setRowCount(11)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_4.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_4.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_4.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_4.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_4.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_4.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_4.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_4.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_4.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_4.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_4.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_4.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_4.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_4.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_4.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_4.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_4.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_4.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_4.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_4.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_4.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_4.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_4.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_4.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_4.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_4.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_4.setHorizontalHeaderItem(15, item)
        self.verticalLayout_39.addWidget(self.tableWidget_script_4)
        self.verticalLayout_40.addLayout(self.verticalLayout_39)
        self.tabWidget_script.addTab(self.tab_script_4, _fromUtf8(""))
        self.tab_script_5 = QtGui.QWidget()
        self.tab_script_5.setObjectName(_fromUtf8("tab_script_5"))
        self.verticalLayout_42 = QtGui.QVBoxLayout(self.tab_script_5)
        self.verticalLayout_42.setMargin(0)
        self.verticalLayout_42.setObjectName(_fromUtf8("verticalLayout_42"))
        self.verticalLayout_41 = QtGui.QVBoxLayout()
        self.verticalLayout_41.setObjectName(_fromUtf8("verticalLayout_41"))
        self.tableWidget_script_5 = QtGui.QTableWidget(self.tab_script_5)
        self.tableWidget_script_5.setObjectName(_fromUtf8("tableWidget_script_5"))
        self.tableWidget_script_5.setColumnCount(16)
        self.tableWidget_script_5.setRowCount(11)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_5.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_5.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_5.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_5.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_5.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_5.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_5.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_5.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_5.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_5.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_5.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_5.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_5.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_5.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_5.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_5.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_5.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_5.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_5.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_5.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_5.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_5.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_5.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_5.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_5.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_5.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_5.setHorizontalHeaderItem(15, item)
        self.verticalLayout_41.addWidget(self.tableWidget_script_5)
        self.verticalLayout_42.addLayout(self.verticalLayout_41)
        self.tabWidget_script.addTab(self.tab_script_5, _fromUtf8(""))
        self.tab_script_6 = QtGui.QWidget()
        self.tab_script_6.setObjectName(_fromUtf8("tab_script_6"))
        self.verticalLayout_44 = QtGui.QVBoxLayout(self.tab_script_6)
        self.verticalLayout_44.setMargin(0)
        self.verticalLayout_44.setObjectName(_fromUtf8("verticalLayout_44"))
        self.verticalLayout_43 = QtGui.QVBoxLayout()
        self.verticalLayout_43.setObjectName(_fromUtf8("verticalLayout_43"))
        self.tableWidget_script_6 = QtGui.QTableWidget(self.tab_script_6)
        self.tableWidget_script_6.setObjectName(_fromUtf8("tableWidget_script_6"))
        self.tableWidget_script_6.setColumnCount(16)
        self.tableWidget_script_6.setRowCount(11)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_6.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_6.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_6.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_6.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_6.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_6.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_6.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_6.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_6.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_6.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_6.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_6.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_6.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_6.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_6.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_6.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_6.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_6.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_6.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_6.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_6.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_6.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_6.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_6.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_6.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_6.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_script_6.setHorizontalHeaderItem(15, item)
        self.verticalLayout_43.addWidget(self.tableWidget_script_6)
        self.verticalLayout_44.addLayout(self.verticalLayout_43)
        self.tabWidget_script.addTab(self.tab_script_6, _fromUtf8(""))
        self.verticalLayout_6.addWidget(self.tabWidget_script)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_effect = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_effect.setTitle(_fromUtf8(""))
        self.groupBox_effect.setObjectName(_fromUtf8("groupBox_effect"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_effect)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.scrollArea_effect = QtGui.QScrollArea(self.groupBox_effect)
        self.scrollArea_effect.setWidgetResizable(True)
        self.scrollArea_effect.setObjectName(_fromUtf8("scrollArea_effect"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1070, 87))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_22.setMargin(0)
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.verticalLayout_22.addLayout(self.verticalLayout_12)
        self.scrollArea_effect.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_10.addWidget(self.scrollArea_effect)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.verticalLayout.addWidget(self.groupBox_effect)
        self.groupBox_wave = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_wave.setObjectName(_fromUtf8("groupBox_wave"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBox_wave)
        self.verticalLayout_13.setMargin(0)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.scrollArea_wave = QtGui.QScrollArea(self.groupBox_wave)
        self.scrollArea_wave.setWidgetResizable(True)
        self.scrollArea_wave.setObjectName(_fromUtf8("scrollArea_wave"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1070, 120))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_13.setMargin(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.horizontalLayout_13.addLayout(self.verticalLayout_23)
        self.scrollArea_wave.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_11.addWidget(self.scrollArea_wave)
        self.verticalLayout_13.addLayout(self.horizontalLayout_11)
        self.verticalLayout.addWidget(self.groupBox_wave)
        self.groupBox_bottom = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_bottom.setTitle(_fromUtf8(""))
        self.groupBox_bottom.setObjectName(_fromUtf8("groupBox_bottom"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_bottom)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.bottom_hlayout = QtGui.QHBoxLayout()
        self.bottom_hlayout.setObjectName(_fromUtf8("bottom_hlayout"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pointer_left_btn = QtGui.QPushButton(self.groupBox_bottom)
        self.pointer_left_btn.setMaximumSize(QtCore.QSize(23, 16777215))
        self.pointer_left_btn.setObjectName(_fromUtf8("pointer_left_btn"))
        self.horizontalLayout_5.addWidget(self.pointer_left_btn)
        self.pointer_right_btn = QtGui.QPushButton(self.groupBox_bottom)
        self.pointer_right_btn.setMaximumSize(QtCore.QSize(23, 16777215))
        self.pointer_right_btn.setObjectName(_fromUtf8("pointer_right_btn"))
        self.horizontalLayout_5.addWidget(self.pointer_right_btn)
        self.wave_zoom_out_btn = QtGui.QPushButton(self.groupBox_bottom)
        self.wave_zoom_out_btn.setMaximumSize(QtCore.QSize(23, 16777215))
        self.wave_zoom_out_btn.setObjectName(_fromUtf8("wave_zoom_out_btn"))
        self.horizontalLayout_5.addWidget(self.wave_zoom_out_btn)
        self.wave_zoom_in_btn = QtGui.QPushButton(self.groupBox_bottom)
        self.wave_zoom_in_btn.setMaximumSize(QtCore.QSize(23, 16777215))
        self.wave_zoom_in_btn.setObjectName(_fromUtf8("wave_zoom_in_btn"))
        self.horizontalLayout_5.addWidget(self.wave_zoom_in_btn)
        self.zoom_out_btn = QtGui.QPushButton(self.groupBox_bottom)
        self.zoom_out_btn.setMaximumSize(QtCore.QSize(23, 16777215))
        self.zoom_out_btn.setObjectName(_fromUtf8("zoom_out_btn"))
        self.horizontalLayout_5.addWidget(self.zoom_out_btn)
        self.zoom_in_btn = QtGui.QPushButton(self.groupBox_bottom)
        self.zoom_in_btn.setMaximumSize(QtCore.QSize(23, 16777215))
        self.zoom_in_btn.setObjectName(_fromUtf8("zoom_in_btn"))
        self.horizontalLayout_5.addWidget(self.zoom_in_btn)
        self.amp_minus_btn = QtGui.QPushButton(self.groupBox_bottom)
        self.amp_minus_btn.setMaximumSize(QtCore.QSize(23, 16777215))
        self.amp_minus_btn.setObjectName(_fromUtf8("amp_minus_btn"))
        self.horizontalLayout_5.addWidget(self.amp_minus_btn)
        self.amp_plus_btn = QtGui.QPushButton(self.groupBox_bottom)
        self.amp_plus_btn.setMaximumSize(QtCore.QSize(23, 16777215))
        self.amp_plus_btn.setObjectName(_fromUtf8("amp_plus_btn"))
        self.horizontalLayout_5.addWidget(self.amp_plus_btn)
        self.match_end_btn = QtGui.QPushButton(self.groupBox_bottom)
        self.match_end_btn.setMaximumSize(QtCore.QSize(23, 16777215))
        self.match_end_btn.setObjectName(_fromUtf8("match_end_btn"))
        self.horizontalLayout_5.addWidget(self.match_end_btn)
        self.normal_mode_btn = QtGui.QPushButton(self.groupBox_bottom)
        self.normal_mode_btn.setMaximumSize(QtCore.QSize(23, 16777215))
        self.normal_mode_btn.setObjectName(_fromUtf8("normal_mode_btn"))
        self.horizontalLayout_5.addWidget(self.normal_mode_btn)
        self.replace_mode_btn = QtGui.QPushButton(self.groupBox_bottom)
        self.replace_mode_btn.setMaximumSize(QtCore.QSize(23, 16777215))
        self.replace_mode_btn.setObjectName(_fromUtf8("replace_mode_btn"))
        self.horizontalLayout_5.addWidget(self.replace_mode_btn)
        self.music_mode_btn = QtGui.QPushButton(self.groupBox_bottom)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.music_mode_btn.sizePolicy().hasHeightForWidth())
        self.music_mode_btn.setSizePolicy(sizePolicy)
        self.music_mode_btn.setMaximumSize(QtCore.QSize(23, 16777215))
        self.music_mode_btn.setObjectName(_fromUtf8("music_mode_btn"))
        self.horizontalLayout_5.addWidget(self.music_mode_btn)
        self.music_play_btn = QtGui.QPushButton(self.groupBox_bottom)
        self.music_play_btn.setMaximumSize(QtCore.QSize(23, 16777215))
        self.music_play_btn.setObjectName(_fromUtf8("music_play_btn"))
        self.horizontalLayout_5.addWidget(self.music_play_btn)
        self.music_pause_btn = QtGui.QPushButton(self.groupBox_bottom)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.music_pause_btn.sizePolicy().hasHeightForWidth())
        self.music_pause_btn.setSizePolicy(sizePolicy)
        self.music_pause_btn.setMaximumSize(QtCore.QSize(23, 16777215))
        self.music_pause_btn.setObjectName(_fromUtf8("music_pause_btn"))
        self.horizontalLayout_5.addWidget(self.music_pause_btn)
        self.music_stop_btn = QtGui.QPushButton(self.groupBox_bottom)
        self.music_stop_btn.setMaximumSize(QtCore.QSize(23, 16777215))
        self.music_stop_btn.setObjectName(_fromUtf8("music_stop_btn"))
        self.horizontalLayout_5.addWidget(self.music_stop_btn)
        self.verticalLayout_14.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.volume_icon_label = QtGui.QLabel(self.groupBox_bottom)
        self.volume_icon_label.setMaximumSize(QtCore.QSize(25, 25))
        self.volume_icon_label.setObjectName(_fromUtf8("volume_icon_label"))
        self.horizontalLayout_4.addWidget(self.volume_icon_label)
        self.volume_slider = QtGui.QSlider(self.groupBox_bottom)
        self.volume_slider.setOrientation(QtCore.Qt.Horizontal)
        self.volume_slider.setObjectName(_fromUtf8("volume_slider"))
        self.horizontalLayout_4.addWidget(self.volume_slider)
        spacerItem = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.balance_left_label = QtGui.QLabel(self.groupBox_bottom)
        self.balance_left_label.setMaximumSize(QtCore.QSize(25, 25))
        self.balance_left_label.setObjectName(_fromUtf8("balance_left_label"))
        self.horizontalLayout_4.addWidget(self.balance_left_label)
        self.balance_slider = QtGui.QSlider(self.groupBox_bottom)
        self.balance_slider.setOrientation(QtCore.Qt.Horizontal)
        self.balance_slider.setObjectName(_fromUtf8("balance_slider"))
        self.horizontalLayout_4.addWidget(self.balance_slider)
        self.balance_right_label = QtGui.QLabel(self.groupBox_bottom)
        self.balance_right_label.setMaximumSize(QtCore.QSize(25, 25))
        self.balance_right_label.setObjectName(_fromUtf8("balance_right_label"))
        self.horizontalLayout_4.addWidget(self.balance_right_label)
        self.verticalLayout_14.addLayout(self.horizontalLayout_4)
        self.bottom_hlayout.addLayout(self.verticalLayout_14)
        spacerItem1 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.bottom_hlayout.addItem(spacerItem1)
        self.groupBox_time = QtGui.QGroupBox(self.groupBox_bottom)
        self.groupBox_time.setMaximumSize(QtCore.QSize(16777215, 65))
        self.groupBox_time.setObjectName(_fromUtf8("groupBox_time"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_time)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lineEdit_time = QtGui.QLineEdit(self.groupBox_time)
        self.lineEdit_time.setObjectName(_fromUtf8("lineEdit_time"))
        self.horizontalLayout_6.addWidget(self.lineEdit_time)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.bottom_hlayout.addWidget(self.groupBox_time)
        self.groupBox_SMPTE = QtGui.QGroupBox(self.groupBox_bottom)
        self.groupBox_SMPTE.setMaximumSize(QtCore.QSize(16777215, 65))
        self.groupBox_SMPTE.setObjectName(_fromUtf8("groupBox_SMPTE"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.groupBox_SMPTE)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.lineEdit_SMPTE = QtGui.QLineEdit(self.groupBox_SMPTE)
        self.lineEdit_SMPTE.setObjectName(_fromUtf8("lineEdit_SMPTE"))
        self.horizontalLayout_8.addWidget(self.lineEdit_SMPTE)
        self.verticalLayout_16.addLayout(self.horizontalLayout_8)
        self.bottom_hlayout.addWidget(self.groupBox_SMPTE)
        self.groupBox_dt = QtGui.QGroupBox(self.groupBox_bottom)
        self.groupBox_dt.setMaximumSize(QtCore.QSize(16777215, 65))
        self.groupBox_dt.setObjectName(_fromUtf8("groupBox_dt"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.groupBox_dt)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.lineEdit_dt = QtGui.QLineEdit(self.groupBox_dt)
        self.lineEdit_dt.setObjectName(_fromUtf8("lineEdit_dt"))
        self.verticalLayout_15.addWidget(self.lineEdit_dt)
        self.verticalLayout_17.addLayout(self.verticalLayout_15)
        self.bottom_hlayout.addWidget(self.groupBox_dt)
        self.groupBox_price = QtGui.QGroupBox(self.groupBox_bottom)
        self.groupBox_price.setMaximumSize(QtCore.QSize(16777215, 90))
        self.groupBox_price.setObjectName(_fromUtf8("groupBox_price"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.groupBox_price)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_4 = QtGui.QLabel(self.groupBox_price)
        self.label_4.setMaximumSize(QtCore.QSize(25, 25))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_10.addWidget(self.label_4)
        self.lineEdit_price = QtGui.QLineEdit(self.groupBox_price)
        self.lineEdit_price.setObjectName(_fromUtf8("lineEdit_price"))
        self.horizontalLayout_10.addWidget(self.lineEdit_price)
        self.verticalLayout_18.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_5 = QtGui.QLabel(self.groupBox_price)
        self.label_5.setMaximumSize(QtCore.QSize(25, 25))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_9.addWidget(self.label_5)
        self.lineEdit_6 = QtGui.QLineEdit(self.groupBox_price)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.horizontalLayout_9.addWidget(self.lineEdit_6)
        self.verticalLayout_18.addLayout(self.horizontalLayout_9)
        self.verticalLayout_19.addLayout(self.verticalLayout_18)
        self.bottom_hlayout.addWidget(self.groupBox_price)
        self.groupBox_Status = QtGui.QGroupBox(self.groupBox_bottom)
        self.groupBox_Status.setMaximumSize(QtCore.QSize(16777215, 90))
        self.groupBox_Status.setObjectName(_fromUtf8("groupBox_Status"))
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.groupBox_Status)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.lineEdit_status = QtGui.QLineEdit(self.groupBox_Status)
        self.lineEdit_status.setObjectName(_fromUtf8("lineEdit_status"))
        self.verticalLayout_20.addWidget(self.lineEdit_status)
        self.progressBar = QtGui.QProgressBar(self.groupBox_Status)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_20.addWidget(self.progressBar)
        self.verticalLayout_21.addLayout(self.verticalLayout_20)
        self.bottom_hlayout.addWidget(self.groupBox_Status)
        self.bottom_hlayout.setStretch(0, 25)
        self.bottom_hlayout.setStretch(2, 10)
        self.bottom_hlayout.setStretch(3, 10)
        self.bottom_hlayout.setStretch(4, 10)
        self.bottom_hlayout.setStretch(5, 15)
        self.bottom_hlayout.setStretch(6, 15)
        self.horizontalLayout_2.addLayout(self.bottom_hlayout)
        self.verticalLayout.addWidget(self.groupBox_bottom)
        self.verticalLayout.setStretch(0, 25)
        self.verticalLayout.setStretch(1, 30)
        self.verticalLayout.setStretch(2, 12)
        self.verticalLayout.setStretch(3, 18)
        self.verticalLayout.setStretch(4, 15)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1096, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuMusic = QtGui.QMenu(self.menubar)
        self.menuMusic.setObjectName(_fromUtf8("menuMusic"))
        self.menuZoom = QtGui.QMenu(self.menubar)
        self.menuZoom.setObjectName(_fromUtf8("menuZoom"))
        self.menuDatabase = QtGui.QMenu(self.menubar)
        self.menuDatabase.setObjectName(_fromUtf8("menuDatabase"))
        self.menuScript = QtGui.QMenu(self.menubar)
        self.menuScript.setObjectName(_fromUtf8("menuScript"))
        self.menuExtras = QtGui.QMenu(self.menubar)
        self.menuExtras.setObjectName(_fromUtf8("menuExtras"))
        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setObjectName(_fromUtf8("menuWindow"))
        self.menuInfo = QtGui.QMenu(self.menubar)
        self.menuInfo.setObjectName(_fromUtf8("menuInfo"))
        self.menuPFM_Advanced = QtGui.QMenu(self.menubar)
        self.menuPFM_Advanced.setObjectName(_fromUtf8("menuPFM_Advanced"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionProjectSave = QtGui.QAction(MainWindow)
        self.actionProjectSave.setObjectName(_fromUtf8("actionProjectSave"))
        self.actionProjectSave_as = QtGui.QAction(MainWindow)
        self.actionProjectSave_as.setObjectName(_fromUtf8("actionProjectSave_as"))
        self.actionImport_music = QtGui.QAction(MainWindow)
        self.actionImport_music.setObjectName(_fromUtf8("actionImport_music"))
        self.actionPlay = QtGui.QAction(MainWindow)
        self.actionPlay.setObjectName(_fromUtf8("actionPlay"))
        self.actionPause = QtGui.QAction(MainWindow)
        self.actionPause.setObjectName(_fromUtf8("actionPause"))
        self.actionStop = QtGui.QAction(MainWindow)
        self.actionStop.setObjectName(_fromUtf8("actionStop"))
        self.actionDelete = QtGui.QAction(MainWindow)
        self.actionDelete.setObjectName(_fromUtf8("actionDelete"))
        self.actionZoom_in = QtGui.QAction(MainWindow)
        self.actionZoom_in.setObjectName(_fromUtf8("actionZoom_in"))
        self.actionZoom_out = QtGui.QAction(MainWindow)
        self.actionZoom_out.setObjectName(_fromUtf8("actionZoom_out"))
        self.actionImport_Database = QtGui.QAction(MainWindow)
        self.actionImport_Database.setObjectName(_fromUtf8("actionImport_Database"))
        self.actionSave_Database = QtGui.QAction(MainWindow)
        self.actionSave_Database.setObjectName(_fromUtf8("actionSave_Database"))
        self.actionImport_script = QtGui.QAction(MainWindow)
        self.actionImport_script.setObjectName(_fromUtf8("actionImport_script"))
        self.actionSave_script = QtGui.QAction(MainWindow)
        self.actionSave_script.setObjectName(_fromUtf8("actionSave_script"))
        self.actionMinimize = QtGui.QAction(MainWindow)
        self.actionMinimize.setObjectName(_fromUtf8("actionMinimize"))
        self.actionVersion = QtGui.QAction(MainWindow)
        self.actionVersion.setObjectName(_fromUtf8("actionVersion"))
        self.actionAbout_us = QtGui.QAction(MainWindow)
        self.actionAbout_us.setObjectName(_fromUtf8("actionAbout_us"))
        self.actionDbSave_as = QtGui.QAction(MainWindow)
        self.actionDbSave_as.setObjectName(_fromUtf8("actionDbSave_as"))
        self.actionScriptSave_as = QtGui.QAction(MainWindow)
        self.actionScriptSave_as.setObjectName(_fromUtf8("actionScriptSave_as"))
        self.actionOpenScript = QtGui.QAction(MainWindow)
        self.actionOpenScript.setObjectName(_fromUtf8("actionOpenScript"))
        self.actionNew_project = QtGui.QAction(MainWindow)
        self.actionNew_project.setObjectName(_fromUtf8("actionNew_project"))
        self.actionImport_project = QtGui.QAction(MainWindow)
        self.actionImport_project.setObjectName(_fromUtf8("actionImport_project"))
        self.actionNew_script = QtGui.QAction(MainWindow)
        self.actionNew_script.setObjectName(_fromUtf8("actionNew_script"))
        self.actionNew_Database = QtGui.QAction(MainWindow)
        self.actionNew_Database.setObjectName(_fromUtf8("actionNew_Database"))
        self.menuFile.addAction(self.actionNew_project)
        self.menuFile.addAction(self.actionImport_project)
        self.menuFile.addAction(self.actionProjectSave)
        self.menuFile.addAction(self.actionProjectSave_as)
        self.menuMusic.addAction(self.actionImport_music)
        self.menuMusic.addAction(self.actionPlay)
        self.menuMusic.addAction(self.actionPause)
        self.menuMusic.addAction(self.actionStop)
        self.menuMusic.addAction(self.actionDelete)
        self.menuZoom.addAction(self.actionZoom_in)
        self.menuZoom.addAction(self.actionZoom_out)
        self.menuDatabase.addAction(self.actionNew_Database)
        self.menuDatabase.addAction(self.actionImport_Database)
        self.menuDatabase.addAction(self.actionSave_Database)
        self.menuDatabase.addAction(self.actionDbSave_as)
        self.menuScript.addAction(self.actionNew_script)
        self.menuScript.addAction(self.actionImport_script)
        self.menuScript.addAction(self.actionSave_script)
        self.menuScript.addAction(self.actionScriptSave_as)
        self.menuWindow.addAction(self.actionMinimize)
        self.menuInfo.addAction(self.actionVersion)
        self.menuInfo.addAction(self.actionAbout_us)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuMusic.menuAction())
        self.menubar.addAction(self.menuZoom.menuAction())
        self.menubar.addAction(self.menuDatabase.menuAction())
        self.menubar.addAction(self.menuScript.menuAction())
        self.menubar.addAction(self.menuExtras.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())
        self.menubar.addAction(self.menuPFM_Advanced.menuAction())
        self.toolBar.addAction(self.actionImport_project)
        self.toolBar.addAction(self.actionProjectSave)
        self.toolBar.addAction(self.actionProjectSave_as)
        self.toolBar.addAction(self.actionImport_Database)
        self.toolBar.addAction(self.actionSave_Database)
        self.toolBar.addAction(self.actionDbSave_as)
        self.toolBar.addAction(self.actionImport_script)
        self.toolBar.addAction(self.actionSave_script)
        self.toolBar.addAction(self.actionScriptSave_as)

        self.retranslateUi(MainWindow)
        self.tabWidget_database.setCurrentIndex(5)
        self.tabWidget_script.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Database", None))
        item = self.tableWidget_database1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Type", None))
        item = self.tableWidget_database1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Item", None))
        item = self.tableWidget_database1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Description", None))
        item = self.tableWidget_database1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Size", None))
        item = self.tableWidget_database1.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Stock", None))
        item = self.tableWidget_database1.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Used Effects", None))
        item = self.tableWidget_database1.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Rising Time", None))
        item = self.tableWidget_database1.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Effect1", None))
        item = self.tableWidget_database1.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "C1", None))
        item = self.tableWidget_database1.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "C2", None))
        item = self.tableWidget_database1.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "C3", None))
        self.tabWidget_database.setTabText(self.tabWidget_database.indexOf(self.tab_database_1), _translate("MainWindow", "User Database 1", None))
        item = self.tableWidget_database2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Type", None))
        item = self.tableWidget_database2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Item", None))
        item = self.tableWidget_database2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Description", None))
        item = self.tableWidget_database2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Size", None))
        item = self.tableWidget_database2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Stock", None))
        item = self.tableWidget_database2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Used Effects", None))
        item = self.tableWidget_database2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Rising Time", None))
        item = self.tableWidget_database2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Effect1", None))
        item = self.tableWidget_database2.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "C1", None))
        item = self.tableWidget_database2.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "C2", None))
        item = self.tableWidget_database2.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "C3", None))
        self.tabWidget_database.setTabText(self.tabWidget_database.indexOf(self.tab_database_2), _translate("MainWindow", "User Database 2", None))
        item = self.tableWidget_database3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Type", None))
        item = self.tableWidget_database3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Item", None))
        item = self.tableWidget_database3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Description", None))
        item = self.tableWidget_database3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Size", None))
        item = self.tableWidget_database3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Stock", None))
        item = self.tableWidget_database3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Used Effects", None))
        item = self.tableWidget_database3.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Rising Time", None))
        item = self.tableWidget_database3.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Effect1", None))
        item = self.tableWidget_database3.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "C1", None))
        item = self.tableWidget_database3.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "C2", None))
        item = self.tableWidget_database3.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "C3", None))
        self.tabWidget_database.setTabText(self.tabWidget_database.indexOf(self.tab_database_3), _translate("MainWindow", "User Database 3", None))
        item = self.tableWidget_database4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Type", None))
        item = self.tableWidget_database4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Item", None))
        item = self.tableWidget_database4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Description", None))
        item = self.tableWidget_database4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Size", None))
        item = self.tableWidget_database4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Stock", None))
        item = self.tableWidget_database4.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Used Effects", None))
        item = self.tableWidget_database4.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Rising Time", None))
        item = self.tableWidget_database4.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Effect1", None))
        item = self.tableWidget_database4.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "C1", None))
        item = self.tableWidget_database4.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "C2", None))
        item = self.tableWidget_database4.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "C3", None))
        self.tabWidget_database.setTabText(self.tabWidget_database.indexOf(self.tab_database_4), _translate("MainWindow", "User Database 4", None))
        item = self.tableWidget_database5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Type", None))
        item = self.tableWidget_database5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Item", None))
        item = self.tableWidget_database5.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Description", None))
        item = self.tableWidget_database5.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Size", None))
        item = self.tableWidget_database5.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Stock", None))
        item = self.tableWidget_database5.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Used Effects", None))
        item = self.tableWidget_database5.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Rising Time", None))
        item = self.tableWidget_database5.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Effect1", None))
        item = self.tableWidget_database5.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "C1", None))
        item = self.tableWidget_database5.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "C2", None))
        item = self.tableWidget_database5.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "C3", None))
        self.tabWidget_database.setTabText(self.tabWidget_database.indexOf(self.tab_database_5), _translate("MainWindow", "User Database 5", None))
        item = self.tableWidget_database6.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Type", None))
        item = self.tableWidget_database6.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Item", None))
        item = self.tableWidget_database6.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Description", None))
        item = self.tableWidget_database6.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Size", None))
        item = self.tableWidget_database6.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Stock", None))
        item = self.tableWidget_database6.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Used Effects", None))
        item = self.tableWidget_database6.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Rising Time", None))
        item = self.tableWidget_database6.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Effect1", None))
        item = self.tableWidget_database6.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "C1", None))
        item = self.tableWidget_database6.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "C2", None))
        item = self.tableWidget_database6.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "C3", None))
        self.tabWidget_database.setTabText(self.tabWidget_database.indexOf(self.tab_database_6), _translate("MainWindow", "User Database 6", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Script", None))
        item = self.tableWidget_script_1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Cue", None))
        item = self.tableWidget_script_1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "dt [s]", None))
        item = self.tableWidget_script_1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Step Cue", None))
        item = self.tableWidget_script_1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Step Delay [s]", None))
        item = self.tableWidget_script_1.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Fire Time", None))
        item = self.tableWidget_script_1.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Effect Time", None))
        item = self.tableWidget_script_1.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Rising Time", None))
        item = self.tableWidget_script_1.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Duration 1", None))
        item = self.tableWidget_script_1.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Item", None))
        item = self.tableWidget_script_1.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Description", None))
        item = self.tableWidget_script_1.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Size", None))
        item = self.tableWidget_script_1.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Effect 1", None))
        item = self.tableWidget_script_1.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Color 1", None))
        item = self.tableWidget_script_1.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "C1", None))
        item = self.tableWidget_script_1.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Position", None))
        item = self.tableWidget_script_1.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Angle", None))
        self.tabWidget_script.setTabText(self.tabWidget_script.indexOf(self.tab_script_1), _translate("MainWindow", "User Script 1", None))
        item = self.tableWidget_script_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Cue", None))
        item = self.tableWidget_script_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "dt [s]", None))
        item = self.tableWidget_script_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Step Cue", None))
        item = self.tableWidget_script_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Step Delay [s]", None))
        item = self.tableWidget_script_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Fire Time", None))
        item = self.tableWidget_script_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Effect Time", None))
        item = self.tableWidget_script_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Rising Time", None))
        item = self.tableWidget_script_2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Duration 1", None))
        item = self.tableWidget_script_2.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Item", None))
        item = self.tableWidget_script_2.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Description", None))
        item = self.tableWidget_script_2.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Size", None))
        item = self.tableWidget_script_2.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Effect 1", None))
        item = self.tableWidget_script_2.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Color 1", None))
        item = self.tableWidget_script_2.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "C1", None))
        item = self.tableWidget_script_2.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Position", None))
        item = self.tableWidget_script_2.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Angle", None))
        self.tabWidget_script.setTabText(self.tabWidget_script.indexOf(self.tab_script_2), _translate("MainWindow", "User Script 2", None))
        item = self.tableWidget_script_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Cue", None))
        item = self.tableWidget_script_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "dt [s]", None))
        item = self.tableWidget_script_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Step Cue", None))
        item = self.tableWidget_script_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Step Delay [s]", None))
        item = self.tableWidget_script_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Fire Time", None))
        item = self.tableWidget_script_3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Effect Time", None))
        item = self.tableWidget_script_3.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Rising Time", None))
        item = self.tableWidget_script_3.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Duration 1", None))
        item = self.tableWidget_script_3.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Item", None))
        item = self.tableWidget_script_3.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Description", None))
        item = self.tableWidget_script_3.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Size", None))
        item = self.tableWidget_script_3.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Effect 1", None))
        item = self.tableWidget_script_3.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Color 1", None))
        item = self.tableWidget_script_3.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "C1", None))
        item = self.tableWidget_script_3.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Position", None))
        item = self.tableWidget_script_3.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Angle", None))
        self.tabWidget_script.setTabText(self.tabWidget_script.indexOf(self.tab_script_3), _translate("MainWindow", "User Script 3", None))
        item = self.tableWidget_script_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Cue", None))
        item = self.tableWidget_script_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "dt [s]", None))
        item = self.tableWidget_script_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Step Cue", None))
        item = self.tableWidget_script_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Step Delay [s]", None))
        item = self.tableWidget_script_4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Fire Time", None))
        item = self.tableWidget_script_4.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Effect Time", None))
        item = self.tableWidget_script_4.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Rising Time", None))
        item = self.tableWidget_script_4.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Duration 1", None))
        item = self.tableWidget_script_4.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Item", None))
        item = self.tableWidget_script_4.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Description", None))
        item = self.tableWidget_script_4.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Size", None))
        item = self.tableWidget_script_4.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Effect 1", None))
        item = self.tableWidget_script_4.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Color 1", None))
        item = self.tableWidget_script_4.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "C1", None))
        item = self.tableWidget_script_4.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Position", None))
        item = self.tableWidget_script_4.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Angle", None))
        self.tabWidget_script.setTabText(self.tabWidget_script.indexOf(self.tab_script_4), _translate("MainWindow", "User Script 4", None))
        item = self.tableWidget_script_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Cue", None))
        item = self.tableWidget_script_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "dt [s]", None))
        item = self.tableWidget_script_5.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Step Cue", None))
        item = self.tableWidget_script_5.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Step Delay [s]", None))
        item = self.tableWidget_script_5.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Fire Time", None))
        item = self.tableWidget_script_5.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Effect Time", None))
        item = self.tableWidget_script_5.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Rising Time", None))
        item = self.tableWidget_script_5.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Duration 1", None))
        item = self.tableWidget_script_5.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Item", None))
        item = self.tableWidget_script_5.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Description", None))
        item = self.tableWidget_script_5.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Size", None))
        item = self.tableWidget_script_5.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Effect 1", None))
        item = self.tableWidget_script_5.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Color 1", None))
        item = self.tableWidget_script_5.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "C1", None))
        item = self.tableWidget_script_5.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Position", None))
        item = self.tableWidget_script_5.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Angle", None))
        self.tabWidget_script.setTabText(self.tabWidget_script.indexOf(self.tab_script_5), _translate("MainWindow", "User Script 5", None))
        item = self.tableWidget_script_6.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Cue", None))
        item = self.tableWidget_script_6.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "dt [s]", None))
        item = self.tableWidget_script_6.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Step Cue", None))
        item = self.tableWidget_script_6.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Step Delay [s]", None))
        item = self.tableWidget_script_6.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Fire Time", None))
        item = self.tableWidget_script_6.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Effect Time", None))
        item = self.tableWidget_script_6.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Rising Time", None))
        item = self.tableWidget_script_6.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Duration 1", None))
        item = self.tableWidget_script_6.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Item", None))
        item = self.tableWidget_script_6.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Description", None))
        item = self.tableWidget_script_6.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Size", None))
        item = self.tableWidget_script_6.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Effect 1", None))
        item = self.tableWidget_script_6.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Color 1", None))
        item = self.tableWidget_script_6.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "C1", None))
        item = self.tableWidget_script_6.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Position", None))
        item = self.tableWidget_script_6.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Angle", None))
        self.tabWidget_script.setTabText(self.tabWidget_script.indexOf(self.tab_script_6), _translate("MainWindow", "User Script 6", None))
        self.groupBox_wave.setTitle(_translate("MainWindow", "Wave", None))
        self.pointer_left_btn.setText(_translate("MainWindow", "PushButton", None))
        self.pointer_right_btn.setText(_translate("MainWindow", "PushButton", None))
        self.wave_zoom_out_btn.setText(_translate("MainWindow", "PushButton", None))
        self.wave_zoom_in_btn.setText(_translate("MainWindow", "PushButton", None))
        self.zoom_out_btn.setText(_translate("MainWindow", "PushButton", None))
        self.zoom_in_btn.setText(_translate("MainWindow", "PushButton", None))
        self.amp_minus_btn.setText(_translate("MainWindow", "PushButton", None))
        self.amp_plus_btn.setText(_translate("MainWindow", "PushButton", None))
        self.match_end_btn.setText(_translate("MainWindow", "PushButton", None))
        self.normal_mode_btn.setText(_translate("MainWindow", "PushButton", None))
        self.replace_mode_btn.setText(_translate("MainWindow", "PushButton", None))
        self.music_mode_btn.setText(_translate("MainWindow", "PushButton", None))
        self.music_play_btn.setText(_translate("MainWindow", "PushButton", None))
        self.music_pause_btn.setText(_translate("MainWindow", "PushButton", None))
        self.music_stop_btn.setText(_translate("MainWindow", "PushButton", None))
        self.volume_icon_label.setText(_translate("MainWindow", "TextLabel", None))
        self.balance_left_label.setText(_translate("MainWindow", "TextLabel", None))
        self.balance_right_label.setText(_translate("MainWindow", "TextLabel", None))
        self.groupBox_time.setTitle(_translate("MainWindow", "Time 100 fps", None))
        self.groupBox_SMPTE.setTitle(_translate("MainWindow", "SMPTE 100 fps", None))
        self.groupBox_dt.setTitle(_translate("MainWindow", "dt", None))
        self.groupBox_price.setTitle(_translate("MainWindow", "Price", None))
        self.label_4.setText(_translate("MainWindow", "PP", None))
        self.label_5.setText(_translate("MainWindow", "SP", None))
        self.groupBox_Status.setTitle(_translate("MainWindow", "Status", None))
        self.menuFile.setTitle(_translate("MainWindow", "file", None))
        self.menuMusic.setTitle(_translate("MainWindow", "Music", None))
        self.menuZoom.setTitle(_translate("MainWindow", "Zoom", None))
        self.menuDatabase.setTitle(_translate("MainWindow", "Database", None))
        self.menuScript.setTitle(_translate("MainWindow", "Script", None))
        self.menuExtras.setTitle(_translate("MainWindow", "Extras", None))
        self.menuWindow.setTitle(_translate("MainWindow", "Window", None))
        self.menuInfo.setTitle(_translate("MainWindow", "Info", None))
        self.menuPFM_Advanced.setTitle(_translate("MainWindow", "PFM Advanced", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionProjectSave.setText(_translate("MainWindow", "save project", None))
        self.actionProjectSave_as.setText(_translate("MainWindow", "project save as", None))
        self.actionImport_music.setText(_translate("MainWindow", "import music", None))
        self.actionPlay.setText(_translate("MainWindow", "play", None))
        self.actionPause.setText(_translate("MainWindow", "pause", None))
        self.actionStop.setText(_translate("MainWindow", "stop", None))
        self.actionDelete.setText(_translate("MainWindow", "delete", None))
        self.actionZoom_in.setText(_translate("MainWindow", "zoom in", None))
        self.actionZoom_out.setText(_translate("MainWindow", "zoom out", None))
        self.actionImport_Database.setText(_translate("MainWindow", "import Database", None))
        self.actionSave_Database.setText(_translate("MainWindow", "save Databse", None))
        self.actionImport_script.setText(_translate("MainWindow", "import script", None))
        self.actionSave_script.setText(_translate("MainWindow", "save script", None))
        self.actionMinimize.setText(_translate("MainWindow", "minimize", None))
        self.actionVersion.setText(_translate("MainWindow", "version", None))
        self.actionAbout_us.setText(_translate("MainWindow", "help", None))
        self.actionDbSave_as.setText(_translate("MainWindow", "save as", None))
        self.actionScriptSave_as.setText(_translate("MainWindow", "save as", None))
        self.actionOpenScript.setText(_translate("MainWindow", "Script", None))
        self.actionNew_project.setText(_translate("MainWindow", "new project", None))
        self.actionImport_project.setText(_translate("MainWindow", "import project", None))
        self.actionNew_script.setText(_translate("MainWindow", "new script", None))
        self.actionNew_Database.setText(_translate("MainWindow", "new Database", None))

