# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_projectImport.ui'
#
# Created: Wed Apr 17 15:31:16 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ProjectDialog(object):
    def setupUi(self, ProjectDialog):
        ProjectDialog.setObjectName("ProjectDialog")
        ProjectDialog.resize(675, 435)
        ProjectDialog.setMinimumSize(QtCore.QSize(675, 435))
        ProjectDialog.setMaximumSize(QtCore.QSize(675, 435))
        self.listWidgetProject = QtGui.QListWidget(ProjectDialog)
        self.listWidgetProject.setGeometry(QtCore.QRect(10, 20, 181, 371))
        self.listWidgetProject.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listWidgetProject.setObjectName("listWidgetProject")
        self.groupBoxDetails = QtGui.QGroupBox(ProjectDialog)
        self.groupBoxDetails.setGeometry(QtCore.QRect(200, 10, 460, 383))
        self.groupBoxDetails.setObjectName("groupBoxDetails")
        self.labelTitle = QtGui.QLabel(self.groupBoxDetails)
        self.labelTitle.setGeometry(QtCore.QRect(20, 10, 250, 30))
        self.labelTitle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.labelTitle.setFont(font)
        self.labelTitle.setObjectName("labelTitle")
        self.labelDesigner = QtGui.QLabel(self.groupBoxDetails)
        self.labelDesigner.setGeometry(QtCore.QRect(20, 40, 80, 25))
        self.labelDesigner.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelDesigner.setFrameShadow(QtGui.QFrame.Plain)
        self.labelDesigner.setMidLineWidth(0)
        self.labelDesigner.setText("Designer:")
        self.labelDesigner.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelDesigner.setObjectName("labelDesigner")
        self.labelDuration = QtGui.QLabel(self.groupBoxDetails)
        self.labelDuration.setGeometry(QtCore.QRect(20, 80, 80, 25))
        self.labelDuration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelDuration.setObjectName("labelDuration")
        self.labelMusic = QtGui.QLabel(self.groupBoxDetails)
        self.labelMusic.setGeometry(QtCore.QRect(20, 120, 80, 25))
        self.labelMusic.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelMusic.setObjectName("labelMusic")
        self.labelShellCount = QtGui.QLabel(self.groupBoxDetails)
        self.labelShellCount.setGeometry(QtCore.QRect(20, 160, 80, 25))
        self.labelShellCount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelShellCount.setObjectName("labelShellCount")
        self.labelModule = QtGui.QLabel(self.groupBoxDetails)
        self.labelModule.setGeometry(QtCore.QRect(20, 200, 80, 25))
        self.labelModule.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelModule.setObjectName("labelModule")
        self.labelDescription = QtGui.QLabel(self.groupBoxDetails)
        self.labelDescription.setGeometry(QtCore.QRect(20, 240, 80, 25))
        self.labelDescription.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelDescription.setFrameShadow(QtGui.QFrame.Plain)
        self.labelDescription.setMidLineWidth(0)
        self.labelDescription.setText("Description:")
        self.labelDescription.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelDescription.setObjectName("labelDescription")
        self.textEditDescription = QtGui.QTextEdit(self.groupBoxDetails)
        self.textEditDescription.setEnabled(False)
        self.textEditDescription.setGeometry(QtCore.QRect(130, 240, 280, 131))
        self.textEditDescription.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEditDescription.setObjectName("textEditDescription")
        self.lineEditDesigner = QtGui.QLineEdit(self.groupBoxDetails)
        self.lineEditDesigner.setEnabled(False)
        self.lineEditDesigner.setGeometry(QtCore.QRect(130, 40, 280, 25))
        self.lineEditDesigner.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditDesigner.setObjectName("lineEditDesigner")
        self.lineEditDuration = QtGui.QLineEdit(self.groupBoxDetails)
        self.lineEditDuration.setEnabled(False)
        self.lineEditDuration.setGeometry(QtCore.QRect(130, 80, 280, 25))
        self.lineEditDuration.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditDuration.setObjectName("lineEditDuration")
        self.lineEditMusic = QtGui.QLineEdit(self.groupBoxDetails)
        self.lineEditMusic.setEnabled(False)
        self.lineEditMusic.setGeometry(QtCore.QRect(130, 120, 280, 25))
        self.lineEditMusic.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditMusic.setObjectName("lineEditMusic")
        self.lineEditShellCount = QtGui.QLineEdit(self.groupBoxDetails)
        self.lineEditShellCount.setEnabled(False)
        self.lineEditShellCount.setGeometry(QtCore.QRect(130, 160, 280, 25))
        self.lineEditShellCount.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditShellCount.setObjectName("lineEditShellCount")
        self.lineEditModuleCount = QtGui.QLineEdit(self.groupBoxDetails)
        self.lineEditModuleCount.setEnabled(False)
        self.lineEditModuleCount.setGeometry(QtCore.QRect(130, 200, 280, 25))
        self.lineEditModuleCount.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditModuleCount.setObjectName("lineEditModuleCount")
        self.pushButtonImport = QtGui.QPushButton(ProjectDialog)
        self.pushButtonImport.setGeometry(QtCore.QRect(10, 400, 75, 30))
        self.pushButtonImport.setObjectName("pushButtonImport")
        self.pushButtonDelete = QtGui.QPushButton(ProjectDialog)
        self.pushButtonDelete.setGeometry(QtCore.QRect(110, 400, 75, 30))
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.pushButtonClose = QtGui.QPushButton(ProjectDialog)
        self.pushButtonClose.setGeometry(QtCore.QRect(580, 400, 75, 30))
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.pushButtonSave = QtGui.QPushButton(ProjectDialog)
        self.pushButtonSave.setGeometry(QtCore.QRect(500, 400, 75, 30))
        self.pushButtonSave.setObjectName("pushButtonSave")

        self.retranslateUi(ProjectDialog)
        QtCore.QMetaObject.connectSlotsByName(ProjectDialog)

    def retranslateUi(self, ProjectDialog):
        ProjectDialog.setWindowTitle(QtGui.QApplication.translate("ProjectDialog", "Show Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxDetails.setTitle(QtGui.QApplication.translate("ProjectDialog", "Details", None, QtGui.QApplication.UnicodeUTF8))
#        self.labelTitle.setText(QtGui.QApplication.translate("ProjectDialog", "title:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDuration.setText(QtGui.QApplication.translate("ProjectDialog", "Duration:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMusic.setText(QtGui.QApplication.translate("ProjectDialog", "Music:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelShellCount.setText(QtGui.QApplication.translate("ProjectDialog", "Shell Count:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelModule.setText(QtGui.QApplication.translate("ProjectDialog", "Module Count:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonImport.setText(QtGui.QApplication.translate("ProjectDialog", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDelete.setText(QtGui.QApplication.translate("ProjectDialog", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonClose.setText(QtGui.QApplication.translate("ProjectDialog", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSave.setText(QtGui.QApplication.translate("ProjectDialog", "Save", None, QtGui.QApplication.UnicodeUTF8))

