# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainWindow1.ui'
#
# Created: Tue Mar 12 15:47:55 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
from Frontend import mainWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1243, 888)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetDatabase = mainWidget.MainWidget()
        self.verticalLayout.addWidget(self.widgetDatabase)
        self.groupBox_effect = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_effect.setTitle("")
        self.groupBox_effect.setObjectName("groupBox_effect")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_effect)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.scrollArea_effect = QtGui.QScrollArea(self.groupBox_effect)
        self.scrollArea_effect.setWidgetResizable(True)
        self.scrollArea_effect.setObjectName("scrollArea_effect")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1217, 139))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_22.addLayout(self.verticalLayout_12)
        self.scrollArea_effect.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_10.addWidget(self.scrollArea_effect)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.verticalLayout.addWidget(self.groupBox_effect)
        self.groupBox_wave = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_wave.setObjectName("groupBox_wave")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBox_wave)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.scrollArea_wave = QtGui.QScrollArea(self.groupBox_wave)
        self.scrollArea_wave.setWidgetResizable(True)
        self.scrollArea_wave.setObjectName("scrollArea_wave")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1217, 79))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_13.addLayout(self.verticalLayout_23)
        self.scrollArea_wave.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_11.addWidget(self.scrollArea_wave)
        self.verticalLayout_13.addLayout(self.horizontalLayout_11)
        self.verticalLayout.addWidget(self.groupBox_wave)
        self.groupBox_bottom = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_bottom.setTitle("")
        self.groupBox_bottom.setObjectName("groupBox_bottom")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_bottom)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bottom_hlayout = QtGui.QHBoxLayout()
        self.bottom_hlayout.setObjectName("bottom_hlayout")
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pointer_left_btn = QtGui.QPushButton(self.groupBox_bottom)
        self.pointer_left_btn.setMinimumSize(QtCore.QSize(25, 25))
        self.pointer_left_btn.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pointer_left_btn.setObjectName("pointer_left_btn")
        self.horizontalLayout_5.addWidget(self.pointer_left_btn)
        self.pointer_right_btn = QtGui.QPushButton(self.groupBox_bottom)
        self.pointer_right_btn.setMinimumSize(QtCore.QSize(25, 25))
        self.pointer_right_btn.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pointer_right_btn.setObjectName("pointer_right_btn")
        self.horizontalLayout_5.addWidget(self.pointer_right_btn)
        self.wave_zoom_out_btn = QtGui.QPushButton(self.groupBox_bottom)
        self.wave_zoom_out_btn.setMinimumSize(QtCore.QSize(25, 25))
        self.wave_zoom_out_btn.setMaximumSize(QtCore.QSize(25, 16777215))
        self.wave_zoom_out_btn.setObjectName("wave_zoom_out_btn")
        self.horizontalLayout_5.addWidget(self.wave_zoom_out_btn)
        self.wave_zoom_in_btn = QtGui.QPushButton(self.groupBox_bottom)
        self.wave_zoom_in_btn.setMinimumSize(QtCore.QSize(25, 25))
        self.wave_zoom_in_btn.setMaximumSize(QtCore.QSize(25, 16777215))
        self.wave_zoom_in_btn.setObjectName("wave_zoom_in_btn")
        self.horizontalLayout_5.addWidget(self.wave_zoom_in_btn)
        self.zoom_out_btn = QtGui.QPushButton(self.groupBox_bottom)
        self.zoom_out_btn.setMaximumSize(QtCore.QSize(23, 16777215))
        self.zoom_out_btn.setObjectName("zoom_out_btn")
        self.horizontalLayout_5.addWidget(self.zoom_out_btn)
        self.zoom_in_btn = QtGui.QPushButton(self.groupBox_bottom)
        self.zoom_in_btn.setMaximumSize(QtCore.QSize(23, 16777215))
        self.zoom_in_btn.setObjectName("zoom_in_btn")
        self.horizontalLayout_5.addWidget(self.zoom_in_btn)
        self.amp_minus_btn = QtGui.QPushButton(self.groupBox_bottom)
        self.amp_minus_btn.setMaximumSize(QtCore.QSize(23, 16777215))
        self.amp_minus_btn.setObjectName("amp_minus_btn")
        self.horizontalLayout_5.addWidget(self.amp_minus_btn)
        self.amp_plus_btn = QtGui.QPushButton(self.groupBox_bottom)
        self.amp_plus_btn.setMaximumSize(QtCore.QSize(23, 16777215))
        self.amp_plus_btn.setObjectName("amp_plus_btn")
        self.horizontalLayout_5.addWidget(self.amp_plus_btn)
        self.match_end_btn = QtGui.QPushButton(self.groupBox_bottom)
        self.match_end_btn.setMaximumSize(QtCore.QSize(23, 16777215))
        self.match_end_btn.setObjectName("match_end_btn")
        self.horizontalLayout_5.addWidget(self.match_end_btn)
        self.normal_mode_btn = QtGui.QPushButton(self.groupBox_bottom)
        self.normal_mode_btn.setMaximumSize(QtCore.QSize(23, 16777215))
        self.normal_mode_btn.setObjectName("normal_mode_btn")
        self.horizontalLayout_5.addWidget(self.normal_mode_btn)
        self.replace_mode_btn = QtGui.QPushButton(self.groupBox_bottom)
        self.replace_mode_btn.setMaximumSize(QtCore.QSize(23, 16777215))
        self.replace_mode_btn.setObjectName("replace_mode_btn")
        self.horizontalLayout_5.addWidget(self.replace_mode_btn)
        self.music_mode_btn = QtGui.QPushButton(self.groupBox_bottom)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.music_mode_btn.sizePolicy().hasHeightForWidth())
        self.music_mode_btn.setSizePolicy(sizePolicy)
        self.music_mode_btn.setMaximumSize(QtCore.QSize(23, 16777215))
        self.music_mode_btn.setObjectName("music_mode_btn")
        self.horizontalLayout_5.addWidget(self.music_mode_btn)
        self.music_play_btn = QtGui.QPushButton(self.groupBox_bottom)
        self.music_play_btn.setMaximumSize(QtCore.QSize(23, 16777215))
        self.music_play_btn.setObjectName("music_play_btn")
        self.horizontalLayout_5.addWidget(self.music_play_btn)
        self.music_pause_btn = QtGui.QPushButton(self.groupBox_bottom)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.music_pause_btn.sizePolicy().hasHeightForWidth())
        self.music_pause_btn.setSizePolicy(sizePolicy)
        self.music_pause_btn.setMaximumSize(QtCore.QSize(23, 16777215))
        self.music_pause_btn.setObjectName("music_pause_btn")
        self.horizontalLayout_5.addWidget(self.music_pause_btn)
        self.music_stop_btn = QtGui.QPushButton(self.groupBox_bottom)
        self.music_stop_btn.setMaximumSize(QtCore.QSize(23, 16777215))
        self.music_stop_btn.setObjectName("music_stop_btn")
        self.horizontalLayout_5.addWidget(self.music_stop_btn)
        self.verticalLayout_14.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.volume_icon_label = QtGui.QLabel(self.groupBox_bottom)
        self.volume_icon_label.setMaximumSize(QtCore.QSize(25, 25))
        self.volume_icon_label.setObjectName("volume_icon_label")
        self.horizontalLayout_4.addWidget(self.volume_icon_label)
        self.volume_slider = QtGui.QSlider(self.groupBox_bottom)
        self.volume_slider.setOrientation(QtCore.Qt.Horizontal)
        self.volume_slider.setObjectName("volume_slider")
        self.horizontalLayout_4.addWidget(self.volume_slider)
        spacerItem = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.balance_left_label = QtGui.QLabel(self.groupBox_bottom)
        self.balance_left_label.setMaximumSize(QtCore.QSize(25, 25))
        self.balance_left_label.setObjectName("balance_left_label")
        self.horizontalLayout_4.addWidget(self.balance_left_label)
        self.balance_slider = QtGui.QSlider(self.groupBox_bottom)
        self.balance_slider.setOrientation(QtCore.Qt.Horizontal)
        self.balance_slider.setObjectName("balance_slider")
        self.horizontalLayout_4.addWidget(self.balance_slider)
        self.balance_right_label = QtGui.QLabel(self.groupBox_bottom)
        self.balance_right_label.setMaximumSize(QtCore.QSize(25, 25))
        self.balance_right_label.setObjectName("balance_right_label")
        self.horizontalLayout_4.addWidget(self.balance_right_label)
        self.verticalLayout_14.addLayout(self.horizontalLayout_4)
        self.bottom_hlayout.addLayout(self.verticalLayout_14)
        spacerItem1 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.bottom_hlayout.addItem(spacerItem1)
        self.groupBox_time = QtGui.QGroupBox(self.groupBox_bottom)
        self.groupBox_time.setMaximumSize(QtCore.QSize(16777215, 65))
        self.groupBox_time.setObjectName("groupBox_time")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_time)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_time = QtGui.QLineEdit(self.groupBox_time)
        self.lineEdit_time.setObjectName("lineEdit_time")
        self.horizontalLayout_6.addWidget(self.lineEdit_time)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.bottom_hlayout.addWidget(self.groupBox_time)
        self.groupBox_SMPTE = QtGui.QGroupBox(self.groupBox_bottom)
        self.groupBox_SMPTE.setMaximumSize(QtCore.QSize(16777215, 65))
        self.groupBox_SMPTE.setObjectName("groupBox_SMPTE")
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.groupBox_SMPTE)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEdit_SMPTE = QtGui.QLineEdit(self.groupBox_SMPTE)
        self.lineEdit_SMPTE.setObjectName("lineEdit_SMPTE")
        self.horizontalLayout_8.addWidget(self.lineEdit_SMPTE)
        self.verticalLayout_16.addLayout(self.horizontalLayout_8)
        self.bottom_hlayout.addWidget(self.groupBox_SMPTE)
        self.groupBox_dt = QtGui.QGroupBox(self.groupBox_bottom)
        self.groupBox_dt.setMaximumSize(QtCore.QSize(16777215, 65))
        self.groupBox_dt.setObjectName("groupBox_dt")
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.groupBox_dt)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.lineEdit_dt = QtGui.QLineEdit(self.groupBox_dt)
        self.lineEdit_dt.setObjectName("lineEdit_dt")
        self.verticalLayout_15.addWidget(self.lineEdit_dt)
        self.verticalLayout_17.addLayout(self.verticalLayout_15)
        self.bottom_hlayout.addWidget(self.groupBox_dt)
        self.groupBox_price = QtGui.QGroupBox(self.groupBox_bottom)
        self.groupBox_price.setMaximumSize(QtCore.QSize(16777215, 90))
        self.groupBox_price.setObjectName("groupBox_price")
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.groupBox_price)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_4 = QtGui.QLabel(self.groupBox_price)
        self.label_4.setMaximumSize(QtCore.QSize(25, 25))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        self.lineEdit_price = QtGui.QLineEdit(self.groupBox_price)
        self.lineEdit_price.setObjectName("lineEdit_price")
        self.horizontalLayout_10.addWidget(self.lineEdit_price)
        self.verticalLayout_18.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtGui.QLabel(self.groupBox_price)
        self.label_5.setMaximumSize(QtCore.QSize(25, 25))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.lineEdit_6 = QtGui.QLineEdit(self.groupBox_price)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_9.addWidget(self.lineEdit_6)
        self.verticalLayout_18.addLayout(self.horizontalLayout_9)
        self.verticalLayout_19.addLayout(self.verticalLayout_18)
        self.bottom_hlayout.addWidget(self.groupBox_price)
        self.groupBox_Status = QtGui.QGroupBox(self.groupBox_bottom)
        self.groupBox_Status.setMaximumSize(QtCore.QSize(16777215, 90))
        self.groupBox_Status.setObjectName("groupBox_Status")
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.groupBox_Status)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_status = QtGui.QLineEdit(self.groupBox_Status)
        self.lineEdit_status.setObjectName("lineEdit_status")
        self.horizontalLayout.addWidget(self.lineEdit_status)
        self.label = QtGui.QLabel(self.groupBox_Status)
        self.label.setMinimumSize(QtCore.QSize(25, 0))
        self.label.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_20.addLayout(self.horizontalLayout)
        self.progressBar = QtGui.QProgressBar(self.groupBox_Status)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_20.addWidget(self.progressBar)
        self.verticalLayout_21.addLayout(self.verticalLayout_20)
        self.bottom_hlayout.addWidget(self.groupBox_Status)
        self.bottom_hlayout.setStretch(0, 25)
        self.bottom_hlayout.setStretch(2, 10)
        self.bottom_hlayout.setStretch(3, 10)
        self.bottom_hlayout.setStretch(4, 10)
        self.bottom_hlayout.setStretch(5, 15)
        self.bottom_hlayout.setStretch(6, 15)
        self.horizontalLayout_2.addLayout(self.bottom_hlayout)
        self.verticalLayout.addWidget(self.groupBox_bottom)
        self.verticalLayout.setStretch(0, 45)
        self.verticalLayout.setStretch(1, 15)
        self.verticalLayout.setStretch(2, 10)
        self.verticalLayout.setStretch(3, 10)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1243, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuMusic = QtGui.QMenu(self.menubar)
        self.menuMusic.setObjectName("menuMusic")
        self.menuZoom = QtGui.QMenu(self.menubar)
        self.menuZoom.setObjectName("menuZoom")
        self.menuDatabase = QtGui.QMenu(self.menubar)
        self.menuDatabase.setObjectName("menuDatabase")
        self.menuScript = QtGui.QMenu(self.menubar)
        self.menuScript.setObjectName("menuScript")
        self.menuExtras = QtGui.QMenu(self.menubar)
        self.menuExtras.setObjectName("menuExtras")
        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuInfo = QtGui.QMenu(self.menubar)
        self.menuInfo.setObjectName("menuInfo")
        self.menuPFM_Advanced = QtGui.QMenu(self.menubar)
        self.menuPFM_Advanced.setObjectName("menuPFM_Advanced")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionProjectSave = QtGui.QAction(MainWindow)
        self.actionProjectSave.setObjectName("actionProjectSave")
        self.actionProjectSave_as = QtGui.QAction(MainWindow)
        self.actionProjectSave_as.setObjectName("actionProjectSave_as")
        self.actionImport_music = QtGui.QAction(MainWindow)
        self.actionImport_music.setObjectName("actionImport_music")
        self.actionPlay = QtGui.QAction(MainWindow)
        self.actionPlay.setObjectName("actionPlay")
        self.actionPause = QtGui.QAction(MainWindow)
        self.actionPause.setObjectName("actionPause")
        self.actionStop = QtGui.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionDelete = QtGui.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionZoom_in = QtGui.QAction(MainWindow)
        self.actionZoom_in.setObjectName("actionZoom_in")
        self.actionZoom_out = QtGui.QAction(MainWindow)
        self.actionZoom_out.setObjectName("actionZoom_out")
        self.actionImport_Database = QtGui.QAction(MainWindow)
        self.actionImport_Database.setObjectName("actionImport_Database")
        self.actionSave_Database = QtGui.QAction(MainWindow)
        self.actionSave_Database.setObjectName("actionSave_Database")
        self.actionImport_script = QtGui.QAction(MainWindow)
        self.actionImport_script.setObjectName("actionImport_script")
        self.actionSave_script = QtGui.QAction(MainWindow)
        self.actionSave_script.setObjectName("actionSave_script")
        self.actionMinimize = QtGui.QAction(MainWindow)
        self.actionMinimize.setObjectName("actionMinimize")
        self.actionVersion = QtGui.QAction(MainWindow)
        self.actionVersion.setObjectName("actionVersion")
        self.actionAbout_us = QtGui.QAction(MainWindow)
        self.actionAbout_us.setObjectName("actionAbout_us")
        self.actionDbSave_as = QtGui.QAction(MainWindow)
        self.actionDbSave_as.setObjectName("actionDbSave_as")
        self.actionScriptSave_as = QtGui.QAction(MainWindow)
        self.actionScriptSave_as.setObjectName("actionScriptSave_as")
        self.actionOpenScript = QtGui.QAction(MainWindow)
        self.actionOpenScript.setObjectName("actionOpenScript")
        self.actionNew_project = QtGui.QAction(MainWindow)
        self.actionNew_project.setObjectName("actionNew_project")
        self.actionImport_project = QtGui.QAction(MainWindow)
        self.actionImport_project.setObjectName("actionImport_project")
        self.actionNew_script = QtGui.QAction(MainWindow)
        self.actionNew_script.setObjectName("actionNew_script")
        self.actionNew_Database = QtGui.QAction(MainWindow)
        self.actionNew_Database.setObjectName("actionNew_Database")
        self.menuFile.addAction(self.actionNew_project)
        self.menuFile.addAction(self.actionImport_project)
        self.menuFile.addAction(self.actionProjectSave)
        self.menuFile.addAction(self.actionProjectSave_as)
        self.menuMusic.addAction(self.actionImport_music)
        self.menuMusic.addAction(self.actionPlay)
        self.menuMusic.addAction(self.actionPause)
        self.menuMusic.addAction(self.actionStop)
        self.menuMusic.addAction(self.actionDelete)
        self.menuZoom.addAction(self.actionZoom_in)
        self.menuZoom.addAction(self.actionZoom_out)
        self.menuDatabase.addAction(self.actionNew_Database)
        self.menuDatabase.addAction(self.actionImport_Database)
        self.menuDatabase.addAction(self.actionSave_Database)
        self.menuDatabase.addAction(self.actionDbSave_as)
        self.menuScript.addAction(self.actionNew_script)
        self.menuScript.addAction(self.actionImport_script)
        self.menuScript.addAction(self.actionSave_script)
        self.menuScript.addAction(self.actionScriptSave_as)
        self.menuWindow.addAction(self.actionMinimize)
        self.menuInfo.addAction(self.actionVersion)
        self.menuInfo.addAction(self.actionAbout_us)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuMusic.menuAction())
        self.menubar.addAction(self.menuZoom.menuAction())
        self.menubar.addAction(self.menuDatabase.menuAction())
        self.menubar.addAction(self.menuScript.menuAction())
        self.menubar.addAction(self.menuExtras.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())
        self.menubar.addAction(self.menuPFM_Advanced.menuAction())
        self.toolBar.addAction(self.actionImport_project)
        self.toolBar.addAction(self.actionProjectSave)
        self.toolBar.addAction(self.actionProjectSave_as)
        self.toolBar.addAction(self.actionImport_Database)
        self.toolBar.addAction(self.actionSave_Database)
        self.toolBar.addAction(self.actionDbSave_as)
        self.toolBar.addAction(self.actionImport_script)
        self.toolBar.addAction(self.actionSave_script)
        self.toolBar.addAction(self.actionScriptSave_as)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_wave.setTitle(QtGui.QApplication.translate("MainWindow", "Wave", None, QtGui.QApplication.UnicodeUTF8))
        self.pointer_left_btn.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pointer_right_btn.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.wave_zoom_out_btn.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.wave_zoom_in_btn.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.zoom_out_btn.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.zoom_in_btn.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.amp_minus_btn.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.amp_plus_btn.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.match_end_btn.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.normal_mode_btn.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.replace_mode_btn.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.music_mode_btn.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.music_play_btn.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.music_pause_btn.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.music_stop_btn.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.volume_icon_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.balance_left_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.balance_right_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_time.setTitle(QtGui.QApplication.translate("MainWindow", "Time 100 fps", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_SMPTE.setTitle(QtGui.QApplication.translate("MainWindow", "SMPTE 100 fps", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_dt.setTitle(QtGui.QApplication.translate("MainWindow", "dt", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_price.setTitle(QtGui.QApplication.translate("MainWindow", "Price", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "PP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "SP", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Status.setTitle(QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "file", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMusic.setTitle(QtGui.QApplication.translate("MainWindow", "Music", None, QtGui.QApplication.UnicodeUTF8))
        self.menuZoom.setTitle(QtGui.QApplication.translate("MainWindow", "Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDatabase.setTitle(QtGui.QApplication.translate("MainWindow", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.menuScript.setTitle(QtGui.QApplication.translate("MainWindow", "Script", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExtras.setTitle(QtGui.QApplication.translate("MainWindow", "Extras", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWindow.setTitle(QtGui.QApplication.translate("MainWindow", "Window", None, QtGui.QApplication.UnicodeUTF8))
        self.menuInfo.setTitle(QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPFM_Advanced.setTitle(QtGui.QApplication.translate("MainWindow", "PFM Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionProjectSave.setText(QtGui.QApplication.translate("MainWindow", "save project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionProjectSave_as.setText(QtGui.QApplication.translate("MainWindow", "project save as", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_music.setText(QtGui.QApplication.translate("MainWindow", "import music", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay.setText(QtGui.QApplication.translate("MainWindow", "play", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPause.setText(QtGui.QApplication.translate("MainWindow", "pause", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop.setText(QtGui.QApplication.translate("MainWindow", "stop", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete.setText(QtGui.QApplication.translate("MainWindow", "delete", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_in.setText(QtGui.QApplication.translate("MainWindow", "zoom in", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_out.setText(QtGui.QApplication.translate("MainWindow", "zoom out", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_Database.setText(QtGui.QApplication.translate("MainWindow", "import Database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Database.setText(QtGui.QApplication.translate("MainWindow", "save Databse", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_script.setText(QtGui.QApplication.translate("MainWindow", "import script", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_script.setText(QtGui.QApplication.translate("MainWindow", "save script", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMinimize.setText(QtGui.QApplication.translate("MainWindow", "minimize", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVersion.setText(QtGui.QApplication.translate("MainWindow", "version", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_us.setText(QtGui.QApplication.translate("MainWindow", "help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDbSave_as.setText(QtGui.QApplication.translate("MainWindow", "save as", None, QtGui.QApplication.UnicodeUTF8))
        self.actionScriptSave_as.setText(QtGui.QApplication.translate("MainWindow", "save as", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenScript.setText(QtGui.QApplication.translate("MainWindow", "Script", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_project.setText(QtGui.QApplication.translate("MainWindow", "new project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_project.setText(QtGui.QApplication.translate("MainWindow", "import project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_script.setText(QtGui.QApplication.translate("MainWindow", "new script", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Database.setText(QtGui.QApplication.translate("MainWindow", "new Database", None, QtGui.QApplication.UnicodeUTF8))

