# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connectTest.ui'
#
# Created: Mon Apr 22 15:58:28 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(466, 264)
        self.labelBoxID = QtGui.QLabel(Dialog)
        self.labelBoxID.setGeometry(QtCore.QRect(30, 20, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.labelBoxID.setFont(font)
        self.labelBoxID.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelBoxID.setObjectName("labelBoxID")
        self.lineEditBoxID = QtGui.QLineEdit(Dialog)
        self.lineEditBoxID.setGeometry(QtCore.QRect(110, 20, 60, 30))
        self.lineEditBoxID.setObjectName("lineEditBoxID")
        self.pushButtonTest = QtGui.QPushButton(Dialog)
        self.pushButtonTest.setGeometry(QtCore.QRect(280, 20, 70, 30))
        self.pushButtonTest.setObjectName("pushButtonTest")
        self.pushButtonReset = QtGui.QPushButton(Dialog)
        self.pushButtonReset.setGeometry(QtCore.QRect(370, 20, 70, 30))
        self.pushButtonReset.setObjectName("pushButtonReset")
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 60, 421, 181))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.radioButton_1 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_1.setEnabled(True)
        self.radioButton_1.setGeometry(QtCore.QRect(30, 50, 20, 20))
        self.radioButton_1.setText("")
        self.radioButton_1.setChecked(False)
        self.radioButton_1.setAutoExclusive(False)
        self.radioButton_1.setObjectName("radioButton_1")
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_2.setEnabled(True)
        self.radioButton_2.setGeometry(QtCore.QRect(80, 50, 20, 20))
        self.radioButton_2.setText("")
        self.radioButton_2.setChecked(False)
        self.radioButton_2.setAutoExclusive(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_3.setEnabled(True)
        self.radioButton_3.setGeometry(QtCore.QRect(130, 50, 20, 20))
        self.radioButton_3.setText("")
        self.radioButton_3.setChecked(False)
        self.radioButton_3.setAutoExclusive(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_4.setEnabled(True)
        self.radioButton_4.setGeometry(QtCore.QRect(180, 50, 20, 20))
        self.radioButton_4.setText("")
        self.radioButton_4.setChecked(False)
        self.radioButton_4.setAutoExclusive(False)
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_5.setEnabled(True)
        self.radioButton_5.setGeometry(QtCore.QRect(230, 50, 20, 20))
        self.radioButton_5.setText("")
        self.radioButton_5.setChecked(False)
        self.radioButton_5.setAutoExclusive(False)
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_6.setEnabled(True)
        self.radioButton_6.setGeometry(QtCore.QRect(280, 50, 20, 20))
        self.radioButton_6.setText("")
        self.radioButton_6.setChecked(False)
        self.radioButton_6.setAutoExclusive(False)
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_7.setEnabled(True)
        self.radioButton_7.setGeometry(QtCore.QRect(330, 50, 20, 20))
        self.radioButton_7.setText("")
        self.radioButton_7.setChecked(False)
        self.radioButton_7.setAutoExclusive(False)
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_8.setEnabled(True)
        self.radioButton_8.setGeometry(QtCore.QRect(380, 50, 20, 20))
        self.radioButton_8.setText("")
        self.radioButton_8.setChecked(False)
        self.radioButton_8.setAutoExclusive(False)
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_9.setEnabled(True)
        self.radioButton_9.setGeometry(QtCore.QRect(30, 130, 20, 20))
        self.radioButton_9.setText("")
        self.radioButton_9.setChecked(False)
        self.radioButton_9.setAutoExclusive(False)
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_10 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_10.setEnabled(True)
        self.radioButton_10.setGeometry(QtCore.QRect(80, 130, 20, 20))
        self.radioButton_10.setText("")
        self.radioButton_10.setChecked(False)
        self.radioButton_10.setAutoExclusive(False)
        self.radioButton_10.setObjectName("radioButton_10")
        self.radioButton_11 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_11.setEnabled(True)
        self.radioButton_11.setGeometry(QtCore.QRect(130, 130, 20, 20))
        self.radioButton_11.setText("")
        self.radioButton_11.setChecked(False)
        self.radioButton_11.setAutoExclusive(False)
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_12 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_12.setEnabled(True)
        self.radioButton_12.setGeometry(QtCore.QRect(180, 130, 20, 20))
        self.radioButton_12.setText("")
        self.radioButton_12.setChecked(False)
        self.radioButton_12.setAutoExclusive(False)
        self.radioButton_12.setObjectName("radioButton_12")
        self.radioButton_13 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_13.setEnabled(True)
        self.radioButton_13.setGeometry(QtCore.QRect(230, 130, 20, 20))
        self.radioButton_13.setText("")
        self.radioButton_13.setChecked(False)
        self.radioButton_13.setAutoExclusive(False)
        self.radioButton_13.setObjectName("radioButton_13")
        self.radioButton_14 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_14.setEnabled(True)
        self.radioButton_14.setGeometry(QtCore.QRect(280, 130, 20, 20))
        self.radioButton_14.setText("")
        self.radioButton_14.setChecked(False)
        self.radioButton_14.setAutoExclusive(False)
        self.radioButton_14.setObjectName("radioButton_14")
        self.radioButton_15 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_15.setEnabled(True)
        self.radioButton_15.setGeometry(QtCore.QRect(330, 130, 20, 20))
        self.radioButton_15.setText("")
        self.radioButton_15.setChecked(False)
        self.radioButton_15.setAutoExclusive(False)
        self.radioButton_15.setObjectName("radioButton_15")
        self.radioButton_16 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_16.setEnabled(True)
        self.radioButton_16.setGeometry(QtCore.QRect(380, 130, 20, 20))
        self.radioButton_16.setText("")
        self.radioButton_16.setChecked(False)
        self.radioButton_16.setAutoExclusive(False)
        self.radioButton_16.setObjectName("radioButton_16")
        self.label_1 = QtGui.QLabel(self.groupBox)
        self.label_1.setGeometry(QtCore.QRect(20, 30, 25, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_1.setFont(font)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(70, 30, 25, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(120, 30, 25, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(170, 30, 25, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(220, 30, 25, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(270, 30, 25, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(320, 30, 25, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(370, 30, 25, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(20, 110, 25, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(70, 110, 25, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(120, 110, 25, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(170, 110, 25, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(220, 110, 25, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(270, 110, 25, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(320, 110, 25, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(370, 110, 25, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "connect", None, QtGui.QApplication.UnicodeUTF8))
        self.labelBoxID.setText(QtGui.QApplication.translate("Dialog", "BoxID:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonTest.setText(QtGui.QApplication.translate("Dialog", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonReset.setText(QtGui.QApplication.translate("Dialog", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Heads", None, QtGui.QApplication.UnicodeUTF8))
        self.label_1.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "13", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "16", None, QtGui.QApplication.UnicodeUTF8))

