# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'databaseEdit.ui'
#
# Created: Tue Mar 12 10:35:03 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_DatabaseDialog(object):
    def setupUi(self, DatabaseDialog):
        DatabaseDialog.setObjectName("DatabaseDialog")
        DatabaseDialog.resize(1002, 405)
        
        
        
        self.groupBoxDbEdit = QtGui.QGroupBox(DatabaseDialog)
        self.groupBoxDbEdit.setGeometry(QtCore.QRect(10, 0, 981, 361))
        self.groupBoxDbEdit.setObjectName("groupBoxDbEdit")
        self.DatabaseEditTab = QtGui.QTabWidget(self.groupBoxDbEdit)
        self.DatabaseEditTab.setGeometry(QtCore.QRect(10, 20, 961, 331))
        self.DatabaseEditTab.setMinimumSize(QtCore.QSize(20, 75))
        self.DatabaseEditTab.setObjectName("DatabaseEditTab")
        self.effectTab = QtGui.QWidget()
        self.effectTab.setAutoFillBackground(True)
        self.effectTab.setObjectName("effectTab")
        self.LabelAlias = QtGui.QLabel(self.effectTab)
        self.LabelAlias.setGeometry(QtCore.QRect(10, 100, 75, 20))
        self.LabelAlias.setMinimumSize(QtCore.QSize(75, 20))
        self.LabelAlias.setObjectName("LabelAlias")
        self.LabelType = QtGui.QLabel(self.effectTab)
        self.LabelType.setGeometry(QtCore.QRect(10, 20, 75, 20))
        self.LabelType.setMinimumSize(QtCore.QSize(75, 20))
        self.LabelType.setObjectName("LabelType")
        self.LabelName = QtGui.QLabel(self.effectTab)
        self.LabelName.setGeometry(QtCore.QRect(10, 60, 75, 20))
        self.LabelName.setMinimumSize(QtCore.QSize(75, 20))
        self.LabelName.setObjectName("LabelName")
        self.descriptLabel = QtGui.QLabel(self.effectTab)
        self.descriptLabel.setGeometry(QtCore.QRect(10, 150, 75, 20))
        self.descriptLabel.setMinimumSize(QtCore.QSize(75, 20))
        self.descriptLabel.setObjectName("descriptLabel")
        self.sizeLabel = QtGui.QLabel(self.effectTab)
        self.sizeLabel.setGeometry(QtCore.QRect(10, 210, 75, 20))
        self.sizeLabel.setMinimumSize(QtCore.QSize(75, 20))
        self.sizeLabel.setObjectName("sizeLabel")
        self.StockLabel = QtGui.QLabel(self.effectTab)
        self.StockLabel.setGeometry(QtCore.QRect(10, 270, 75, 20))
        self.StockLabel.setMinimumSize(QtCore.QSize(75, 20))
        self.StockLabel.setObjectName("StockLabel")
        self.lineEditName = QtGui.QLineEdit(self.effectTab)
        self.lineEditName.setGeometry(QtCore.QRect(80, 60, 113, 20))
        self.lineEditName.setObjectName("lineEditName")
        self.lineEditAlias = QtGui.QLineEdit(self.effectTab)
        self.lineEditAlias.setGeometry(QtCore.QRect(80, 100, 113, 20))
        self.lineEditAlias.setObjectName("lineEditAlias")
        self.lineEdit_descript = QtGui.QLineEdit(self.effectTab)
        self.lineEdit_descript.setGeometry(QtCore.QRect(80, 150, 191, 21))
        self.lineEdit_descript.setObjectName("lineEdit_descript")
        
        self.lineEdit_size = QtGui.QLineEdit(self.effectTab)
        self.lineEdit_size.setGeometry(QtCore.QRect(80, 210, 70, 20))
        self.lineEdit_size.setObjectName("lineEdit_size")
        doubleVal = QtGui.QDoubleValidator()
        self.lineEdit_size.setValidator(doubleVal)
        
        
        self.lineEdit_stock = QtGui.QLineEdit(self.effectTab)
        self.lineEdit_stock.setGeometry(QtCore.QRect(80, 270, 70, 20))
        self.lineEdit_stock.setObjectName("lineEdit_stock")
        intVal = QtGui.QIntValidator()
        self.lineEdit_stock.setValidator(intVal)
        
        self.line = QtGui.QFrame(self.effectTab)
        self.line.setGeometry(QtCore.QRect(410, 10, 16, 281))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.mmLabel = QtGui.QLabel(self.effectTab)
        self.mmLabel.setGeometry(QtCore.QRect(150, 210, 25, 20))
        self.mmLabel.setObjectName("mmLabel")
        
        self.lineEdit_usedEffect = QtGui.QLineEdit(self.effectTab)
        self.lineEdit_usedEffect.setGeometry(QtCore.QRect(280, 210, 100, 20))
        self.lineEdit_usedEffect.setObjectName("lineEdit_usedEffect")
        intVal = QtGui.QIntValidator()
        self.lineEdit_usedEffect.setValidator(intVal)
        
        self.label_effectUsed = QtGui.QLabel(self.effectTab)
        self.label_effectUsed.setGeometry(QtCore.QRect(200, 210, 75, 20))
        self.label_effectUsed.setMinimumSize(QtCore.QSize(75, 20))
        self.label_effectUsed.setObjectName("label_effectUsed")
        self.line_2 = QtGui.QFrame(self.effectTab)
        self.line_2.setGeometry(QtCore.QRect(670, 10, 16, 281))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_effectPrice = QtGui.QLabel(self.effectTab)
        self.label_effectPrice.setGeometry(QtCore.QRect(380, 210, 30, 20))
        self.label_effectPrice.setObjectName("label_effectPrice")
        self.label_min = QtGui.QLabel(self.effectTab)
        self.label_min.setGeometry(QtCore.QRect(200, 240, 75, 20))
        self.label_min.setMinimumSize(QtCore.QSize(75, 20))
        self.label_min.setObjectName("label_min")
        self.label_Best = QtGui.QLabel(self.effectTab)
        self.label_Best.setGeometry(QtCore.QRect(200, 270, 75, 20))
        self.label_Best.setMinimumSize(QtCore.QSize(75, 20))
        self.label_Best.setObjectName("label_Best")
        
        self.lineEdit_Min = QtGui.QLineEdit(self.effectTab)
        self.lineEdit_Min.setGeometry(QtCore.QRect(280, 240, 100, 20))
        self.lineEdit_Min.setObjectName("lineEdit_Min")
        intVal = QtGui.QIntValidator()
        self.lineEdit_Min.setValidator(intVal)
        
        self.lineEdit_Best = QtGui.QLineEdit(self.effectTab)
        self.lineEdit_Best.setGeometry(QtCore.QRect(280, 270, 100, 20))
        self.lineEdit_Best.setObjectName("lineEdit_Best")
        intVal = QtGui.QIntValidator()
        self.lineEdit_Best.setValidator(intVal)
        
        self.label_minPrice = QtGui.QLabel(self.effectTab)
        self.label_minPrice.setGeometry(QtCore.QRect(380, 240, 30, 20))
        self.label_minPrice.setObjectName("label_minPrice")
        self.label_bestPrice = QtGui.QLabel(self.effectTab)
        self.label_bestPrice.setGeometry(QtCore.QRect(380, 270, 30, 20))
        self.label_bestPrice.setObjectName("label_bestPrice")
        self.label_riseTime = QtGui.QLabel(self.effectTab)
        self.label_riseTime.setGeometry(QtCore.QRect(440, 20, 70, 20))
        self.label_riseTime.setMinimumSize(QtCore.QSize(70, 20))
        self.label_riseTime.setObjectName("label_riseTime")
        
        self.lineEdit_riseTime = QtGui.QLineEdit(self.effectTab)
        self.lineEdit_riseTime.setGeometry(QtCore.QRect(510, 20, 80, 20))
        self.lineEdit_riseTime.setObjectName("lineEdit_riseTime")
        doubleVal = QtGui.QDoubleValidator()
        self.lineEdit_riseTime.setValidator(doubleVal)
        
        self.lineEdit_effect1 = QtGui.QLineEdit(self.effectTab)
        self.lineEdit_effect1.setGeometry(QtCore.QRect(510, 70, 120, 20))
        self.lineEdit_effect1.setObjectName("lineEdit_effect1")
        self.lineEdit_durationTime1 = QtGui.QLineEdit(self.effectTab)
        self.lineEdit_durationTime1.setGeometry(QtCore.QRect(510, 150, 80, 20))
        self.lineEdit_durationTime1.setObjectName("lineEdit_durationTime1")
        doubleVal = QtGui.QDoubleValidator()
        self.lineEdit_durationTime1.setValidator(doubleVal)
        
        self.lineEdit_effect2 = QtGui.QLineEdit(self.effectTab)
        self.lineEdit_effect2.setGeometry(QtCore.QRect(510, 190, 120, 20))
        self.lineEdit_effect2.setObjectName("lineEdit_effect2")
        self.lineEdit_durationTime2 = QtGui.QLineEdit(self.effectTab)
        self.lineEdit_durationTime2.setGeometry(QtCore.QRect(510, 270, 80, 20))
        self.lineEdit_durationTime2.setObjectName("lineEdit_durationTime2")
        doubleVal = QtGui.QDoubleValidator()
        self.lineEdit_durationTime2.setValidator(doubleVal)
        
        self.label_risTimeSec = QtGui.QLabel(self.effectTab)
        self.label_risTimeSec.setGeometry(QtCore.QRect(590, 20, 30, 20))
        self.label_risTimeSec.setObjectName("label_risTimeSec")
        self.label_effect1 = QtGui.QLabel(self.effectTab)
        self.label_effect1.setGeometry(QtCore.QRect(440, 70, 70, 20))
        self.label_effect1.setMinimumSize(QtCore.QSize(70, 20))
        self.label_effect1.setObjectName("label_effect1")
        self.label_color1 = QtGui.QLabel(self.effectTab)
        self.label_color1.setGeometry(QtCore.QRect(440, 110, 70, 20))
        self.label_color1.setMinimumSize(QtCore.QSize(70, 20))
        self.label_color1.setObjectName("label_color1")
        self.label_duration1 = QtGui.QLabel(self.effectTab)
        self.label_duration1.setGeometry(QtCore.QRect(440, 150, 70, 20))
        self.label_duration1.setMinimumSize(QtCore.QSize(70, 20))
        self.label_duration1.setObjectName("label_duration1")
        self.label_duration2 = QtGui.QLabel(self.effectTab)
        self.label_duration2.setGeometry(QtCore.QRect(440, 270, 70, 20))
        self.label_duration2.setMinimumSize(QtCore.QSize(70, 20))
        self.label_duration2.setObjectName("label_duration2")
        self.label_effect2 = QtGui.QLabel(self.effectTab)
        self.label_effect2.setGeometry(QtCore.QRect(440, 190, 70, 20))
        self.label_effect2.setMinimumSize(QtCore.QSize(70, 20))
        self.label_effect2.setObjectName("label_effect2")
        self.label_color2 = QtGui.QLabel(self.effectTab)
        self.label_color2.setGeometry(QtCore.QRect(440, 230, 70, 20))
        self.label_color2.setMinimumSize(QtCore.QSize(70, 20))
        self.label_color2.setObjectName("label_color2")
        self.label_druationSeconds = QtGui.QLabel(self.effectTab)
        self.label_druationSeconds.setGeometry(QtCore.QRect(590, 270, 30, 20))
        self.label_druationSeconds.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_druationSeconds.setFrameShadow(QtGui.QFrame.Plain)
        self.label_druationSeconds.setObjectName("label_druationSeconds")
        self.label_durationSeconds = QtGui.QLabel(self.effectTab)
        self.label_durationSeconds.setGeometry(QtCore.QRect(590, 150, 30, 20))
        self.label_durationSeconds.setObjectName("label_durationSeconds")
        self.label_effect3 = QtGui.QLabel(self.effectTab)
        self.label_effect3.setGeometry(QtCore.QRect(710, 40, 80, 20))
        self.label_effect3.setMinimumSize(QtCore.QSize(80, 20))
        self.label_effect3.setObjectName("label_effect3")
        self.lineEdit_effect3 = QtGui.QLineEdit(self.effectTab)
        self.lineEdit_effect3.setGeometry(QtCore.QRect(790, 40, 120, 20))
        self.lineEdit_effect3.setObjectName("lineEdit_effect3")
        self.label_color3 = QtGui.QLabel(self.effectTab)
        self.label_color3.setGeometry(QtCore.QRect(710, 80, 80, 20))
        self.label_color3.setMinimumSize(QtCore.QSize(80, 20))
        self.label_color3.setObjectName("label_color3")
        self.label_duration3 = QtGui.QLabel(self.effectTab)
        self.label_duration3.setGeometry(QtCore.QRect(710, 120, 80, 20))
        self.label_duration3.setMinimumSize(QtCore.QSize(80, 20))
        self.label_duration3.setObjectName("label_duration3")
        self.lineEdit_durationTime3 = QtGui.QLineEdit(self.effectTab)
        self.lineEdit_durationTime3.setGeometry(QtCore.QRect(790, 120, 80, 20))
        self.lineEdit_durationTime3.setObjectName("lineEdit_durationTime3")
        doubleVal = QtGui.QDoubleValidator()
        self.lineEdit_durationTime3.setValidator(doubleVal)
        
        self.label_durationSeconds3 = QtGui.QLabel(self.effectTab)
        self.label_durationSeconds3.setGeometry(QtCore.QRect(870, 120, 30, 20))
        self.label_durationSeconds3.setObjectName("label_durationSeconds3")
        self.label_shots = QtGui.QLabel(self.effectTab)
        self.label_shots.setGeometry(QtCore.QRect(710, 160, 80, 20))
        self.label_shots.setMinimumSize(QtCore.QSize(80, 20))
        self.label_shots.setObjectName("label_shots")
        self.lineEdit_shots = QtGui.QLineEdit(self.effectTab)
        self.lineEdit_shots.setGeometry(QtCore.QRect(790, 160, 80, 20))
        self.lineEdit_shots.setObjectName("lineEdit_shots")
        intVal = QtGui.QIntValidator()
        self.lineEdit_shots.setValidator(intVal)
        
        self.label_application = QtGui.QLabel(self.effectTab)
        self.label_application.setGeometry(QtCore.QRect(710, 210, 80, 20))
        self.label_application.setMinimumSize(QtCore.QSize(80, 20))
        self.label_application.setObjectName("label_application")
        self.radioButton_indoor = QtGui.QRadioButton(self.effectTab)
        self.radioButton_indoor.setGeometry(QtCore.QRect(790, 210, 70, 20))
        self.radioButton_indoor.setObjectName("radioButton_indoor")
        self.radioButton_outdoor = QtGui.QRadioButton(self.effectTab)
        self.radioButton_outdoor.setGeometry(QtCore.QRect(870, 210, 70, 20))
        self.radioButton_outdoor.setChecked(True)
        self.radioButton_outdoor.setObjectName("radioButton_outdoor")
        self.label_riseHeight = QtGui.QLabel(self.effectTab)
        self.label_riseHeight.setGeometry(QtCore.QRect(710, 240, 80, 20))
        self.label_riseHeight.setMinimumSize(QtCore.QSize(80, 20))
        self.label_riseHeight.setObjectName("label_riseHeight")
        self.label_diameter = QtGui.QLabel(self.effectTab)
        self.label_diameter.setGeometry(QtCore.QRect(710, 270, 80, 20))
        self.label_diameter.setMinimumSize(QtCore.QSize(80, 20))
        self.label_diameter.setObjectName("label_diameter")
        self.lineEdit_riseHeight = QtGui.QLineEdit(self.effectTab)
        self.lineEdit_riseHeight.setGeometry(QtCore.QRect(790, 240, 80, 20))
        self.lineEdit_riseHeight.setObjectName("lineEdit_riseHeight")
        intVal = QtGui.QIntValidator()
        self.lineEdit_riseHeight.setValidator(intVal)
        
        self.lineEdit_diameter = QtGui.QLineEdit(self.effectTab)
        self.lineEdit_diameter.setGeometry(QtCore.QRect(790, 270, 80, 20))
        self.lineEdit_diameter.setObjectName("lineEdit_diameter")
        intVal = QtGui.QIntValidator()
        self.lineEdit_diameter.setValidator(intVal)
        
        self.label_50 = QtGui.QLabel(self.effectTab)
        self.label_50.setGeometry(QtCore.QRect(610, 230, 30, 20))
        self.label_50.setMouseTracking(False)
        self.label_50.setAcceptDrops(False)
        self.label_50.setAutoFillBackground(False)
        self.label_50.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_50.setText("")
        self.label_50.setObjectName("label_50")
        self.IconLabel_color2 = QtGui.QLabel(self.effectTab)
        self.IconLabel_color2.setGeometry(QtCore.QRect(590, 230, 20, 20))
        self.IconLabel_color2.setMinimumSize(QtCore.QSize(20, 20))
        self.IconLabel_color2.setFrameShape(QtGui.QFrame.Box)
        self.IconLabel_color2.setFrameShadow(QtGui.QFrame.Sunken)
        self.IconLabel_color2.setText("")
        self.IconLabel_color2.setObjectName("IconLabel_color2")
        self.IconLabel_color1 = QtGui.QLabel(self.effectTab)
        self.IconLabel_color1.setGeometry(QtCore.QRect(590, 110, 20, 20))
        self.IconLabel_color1.setMinimumSize(QtCore.QSize(20, 20))
        self.IconLabel_color1.setFrameShape(QtGui.QFrame.Box)
        self.IconLabel_color1.setFrameShadow(QtGui.QFrame.Sunken)
        self.IconLabel_color1.setText("")
        self.IconLabel_color1.setObjectName("IconLabel_color1")
        self.IconLabel_color3 = QtGui.QLabel(self.effectTab)
        self.IconLabel_color3.setGeometry(QtCore.QRect(870, 80, 20, 20))
        self.IconLabel_color3.setMinimumSize(QtCore.QSize(20, 20))
        self.IconLabel_color3.setFrameShape(QtGui.QFrame.Box)
        self.IconLabel_color3.setFrameShadow(QtGui.QFrame.Sunken)
        self.IconLabel_color3.setText("")
        self.IconLabel_color3.setObjectName("IconLabel_color3")
        self.effectIconLabel = QtGui.QLabel(self.effectTab)
        self.effectIconLabel.setGeometry(QtCore.QRect(240, 10, 140, 130))
        self.effectIconLabel.setMinimumSize(QtCore.QSize(20, 20))
        self.effectIconLabel.setFrameShape(QtGui.QFrame.Box)
        self.effectIconLabel.setFrameShadow(QtGui.QFrame.Sunken)
        self.effectIconLabel.setObjectName("effectIconLabel")
        self.comboBoxColor1 = QtGui.QComboBox(self.effectTab)
        self.comboBoxColor1.setGeometry(QtCore.QRect(510, 110, 70, 20))
        self.comboBoxColor1.setObjectName("comboBoxColor1")
        self.comboBoxColor1.addItem("")
        self.comboBoxColor1.setItemText(0, "")
        self.comboBoxColor1.addItem("")
        self.comboBoxColor1.addItem("")
        self.comboBoxColor1.addItem("")
        self.comboBoxColor1.addItem("")
        self.comboBoxColor1.addItem("")
        self.comboBoxColor1.addItem("")
        self.comboBoxColor1.addItem("")
        self.comboBoxColor1.addItem("")
        self.comboBoxColor1.addItem("")
        self.comboBoxColor2 = QtGui.QComboBox(self.effectTab)
        self.comboBoxColor2.setGeometry(QtCore.QRect(510, 230, 70, 20))
        self.comboBoxColor2.setObjectName("comboBoxColor2")
        self.comboBoxColor2.addItem("")
        self.comboBoxColor2.setItemText(0, "")
        self.comboBoxColor2.addItem("")
        self.comboBoxColor2.addItem("")
        self.comboBoxColor2.addItem("")
        self.comboBoxColor2.addItem("")
        self.comboBoxColor2.addItem("")
        self.comboBoxColor2.addItem("")
        self.comboBoxColor2.addItem("")
        self.comboBoxColor2.addItem("")
        self.comboBoxColor2.addItem("")
        self.comboBoxColor3 = QtGui.QComboBox(self.effectTab)
        self.comboBoxColor3.setGeometry(QtCore.QRect(790, 80, 70, 20))
        self.comboBoxColor3.setObjectName("comboBoxColor3")
        self.comboBoxColor3.addItem("")
        self.comboBoxColor3.setItemText(0, "")
        self.comboBoxColor3.addItem("")
        self.comboBoxColor3.addItem("")
        self.comboBoxColor3.addItem("")
        self.comboBoxColor3.addItem("")
        self.comboBoxColor3.addItem("")
        self.comboBoxColor3.addItem("")
        self.comboBoxColor3.addItem("")
        self.comboBoxColor3.addItem("")
        self.comboBoxColor3.addItem("")
        self.label_risingHeight_m = QtGui.QLabel(self.effectTab)
        self.label_risingHeight_m.setGeometry(QtCore.QRect(880, 240, 20, 20))
        self.label_risingHeight_m.setMinimumSize(QtCore.QSize(20, 20))
        self.label_risingHeight_m.setObjectName("label_risingHeight_m")
        self.label_diameter_m = QtGui.QLabel(self.effectTab)
        self.label_diameter_m.setGeometry(QtCore.QRect(880, 270, 20, 20))
        self.label_diameter_m.setMinimumSize(QtCore.QSize(20, 20))
        self.label_diameter_m.setObjectName("label_diameter_m")
        self.label_stockPrice = QtGui.QLabel(self.effectTab)
        self.label_stockPrice.setGeometry(QtCore.QRect(150, 270, 30, 20))
        self.label_stockPrice.setObjectName("label_stockPrice")
        self.comboBoxType = QtGui.QComboBox(self.effectTab)
        self.comboBoxType.setGeometry(QtCore.QRect(80, 20, 111, 20))
        self.comboBoxType.setObjectName("comboBoxType")
        self.comboBoxType.addItem("")
        self.comboBoxType.addItem("")
        self.comboBoxType.addItem("")
        self.comboBoxType.addItem("")
        self.comboBoxType.addItem("")
        self.comboBoxType.addItem("")
        self.comboBoxType.addItem("")
        self.comboBoxType.addItem("")
        self.comboBoxType.addItem("")
        self.DatabaseEditTab.addTab(self.effectTab, "")
        self.miscellaneTab = QtGui.QWidget()
        self.miscellaneTab.setAutoFillBackground(True)
        self.miscellaneTab.setObjectName("miscellaneTab")
        self.lineEdit_class = QtGui.QLineEdit(self.miscellaneTab)
        self.lineEdit_class.setGeometry(QtCore.QRect(100, 20, 113, 20))
        self.lineEdit_class.setObjectName("lineEdit_class")
        self.label_UNnumber = QtGui.QLabel(self.miscellaneTab)
        self.label_UNnumber.setGeometry(QtCore.QRect(20, 140, 75, 20))
        self.label_UNnumber.setMinimumSize(QtCore.QSize(75, 20))
        self.label_UNnumber.setObjectName("label_UNnumber")
        self.label_class = QtGui.QLabel(self.miscellaneTab)
        self.label_class.setGeometry(QtCore.QRect(20, 20, 75, 20))
        self.label_class.setMinimumSize(QtCore.QSize(75, 20))
        self.label_class.setObjectName("label_class")
        self.label_chiper = QtGui.QLabel(self.miscellaneTab)
        self.label_chiper.setGeometry(QtCore.QRect(20, 180, 75, 20))
        self.label_chiper.setMinimumSize(QtCore.QSize(75, 20))
        self.label_chiper.setObjectName("label_chiper")
        self.label_BAM_Number = QtGui.QLabel(self.miscellaneTab)
        self.label_BAM_Number.setGeometry(QtCore.QRect(20, 60, 75, 20))
        self.label_BAM_Number.setMinimumSize(QtCore.QSize(75, 20))
        self.label_BAM_Number.setObjectName("label_BAM_Number")
        self.label_weightNet = QtGui.QLabel(self.miscellaneTab)
        self.label_weightNet.setGeometry(QtCore.QRect(20, 230, 75, 20))
        self.label_weightNet.setMinimumSize(QtCore.QSize(75, 20))
        self.label_weightNet.setObjectName("label_weightNet")
        self.label_weightGross = QtGui.QLabel(self.miscellaneTab)
        self.label_weightGross.setGeometry(QtCore.QRect(20, 270, 75, 20))
        self.label_weightGross.setMinimumSize(QtCore.QSize(75, 20))
        self.label_weightGross.setObjectName("label_weightGross")
        self.label_ADRclass = QtGui.QLabel(self.miscellaneTab)
        self.label_ADRclass.setGeometry(QtCore.QRect(20, 100, 75, 20))
        self.label_ADRclass.setMinimumSize(QtCore.QSize(75, 20))
        self.label_ADRclass.setObjectName("label_ADRclass")
        self.lineEdit_BAMnumber = QtGui.QLineEdit(self.miscellaneTab)
        self.lineEdit_BAMnumber.setGeometry(QtCore.QRect(100, 60, 113, 20))
        self.lineEdit_BAMnumber.setObjectName("lineEdit_BAMnumber")
        self.lineEdit_ADRclass = QtGui.QLineEdit(self.miscellaneTab)
        self.lineEdit_ADRclass.setGeometry(QtCore.QRect(100, 100, 113, 20))
        self.lineEdit_ADRclass.setObjectName("lineEdit_ADRclass")
        self.lineEdit_UNnumber = QtGui.QLineEdit(self.miscellaneTab)
        self.lineEdit_UNnumber.setGeometry(QtCore.QRect(100, 140, 113, 20))
        self.lineEdit_UNnumber.setObjectName("lineEdit_UNnumber")
        self.lineEdit_chiper = QtGui.QLineEdit(self.miscellaneTab)
        self.lineEdit_chiper.setGeometry(QtCore.QRect(100, 180, 113, 20))
        self.lineEdit_chiper.setObjectName("lineEdit_chiper")
        intVal = QtGui.QIntValidator()
        self.lineEdit_chiper.setValidator(intVal)
        
        self.lineEdit_weightNet = QtGui.QLineEdit(self.miscellaneTab)
        self.lineEdit_weightNet.setGeometry(QtCore.QRect(100, 230, 113, 20))
        self.lineEdit_weightNet.setObjectName("lineEdit_weightNet")
        doubleVal = QtGui.QDoubleValidator()
        self.lineEdit_weightNet.setValidator(doubleVal)
        
        self.lineEdit_weightGross = QtGui.QLineEdit(self.miscellaneTab)
        self.lineEdit_weightGross.setGeometry(QtCore.QRect(100, 270, 113, 20))
        self.lineEdit_weightGross.setObjectName("lineEdit_weightGross")
        doubleVal = QtGui.QDoubleValidator()
        self.lineEdit_weightGross.setValidator(doubleVal)
        
        self.label_weightNetKg = QtGui.QLabel(self.miscellaneTab)
        self.label_weightNetKg.setGeometry(QtCore.QRect(220, 230, 30, 20))
        self.label_weightNetKg.setObjectName("label_weightNetKg")
        self.label_weightGrossKg = QtGui.QLabel(self.miscellaneTab)
        self.label_weightGrossKg.setGeometry(QtCore.QRect(220, 270, 30, 20))
        self.label_weightGrossKg.setObjectName("label_weightGrossKg")
        self.line_3 = QtGui.QFrame(self.miscellaneTab)
        self.line_3.setGeometry(QtCore.QRect(280, 20, 16, 271))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtGui.QFrame(self.miscellaneTab)
        self.line_4.setGeometry(QtCore.QRect(630, 20, 20, 271))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_safeDistance = QtGui.QLabel(self.miscellaneTab)
        self.label_safeDistance.setGeometry(QtCore.QRect(330, 20, 90, 20))
        self.label_safeDistance.setMinimumSize(QtCore.QSize(90, 20))
        self.label_safeDistance.setObjectName("label_safeDistance")
        self.label_HorizSafeDis = QtGui.QLabel(self.miscellaneTab)
        self.label_HorizSafeDis.setGeometry(QtCore.QRect(330, 50, 105, 20))
        self.label_HorizSafeDis.setMinimumSize(QtCore.QSize(105, 20))
        self.label_HorizSafeDis.setObjectName("label_HorizSafeDis")
        self.label_VertSafeDistance = QtGui.QLabel(self.miscellaneTab)
        self.label_VertSafeDistance.setGeometry(QtCore.QRect(330, 80, 105, 20))
        self.label_VertSafeDistance.setMinimumSize(QtCore.QSize(105, 20))
        self.label_VertSafeDistance.setObjectName("label_VertSafeDistance")
        self.label_ShowSimEffectID = QtGui.QLabel(self.miscellaneTab)
        self.label_ShowSimEffectID.setGeometry(QtCore.QRect(330, 110, 105, 20))
        self.label_ShowSimEffectID.setMinimumSize(QtCore.QSize(105, 20))
        self.label_ShowSimEffectID.setObjectName("label_ShowSimEffectID")
        self.label_Rating = QtGui.QLabel(self.miscellaneTab)
        self.label_Rating.setGeometry(QtCore.QRect(330, 140, 105, 20))
        self.label_Rating.setMinimumSize(QtCore.QSize(105, 20))
        self.label_Rating.setObjectName("label_Rating")
        self.label_information = QtGui.QLabel(self.miscellaneTab)
        self.label_information.setGeometry(QtCore.QRect(330, 170, 105, 20))
        self.label_information.setMinimumSize(QtCore.QSize(105, 20))
        self.label_information.setObjectName("label_information")
        self.lineEdit_HorizSafeDistance = QtGui.QLineEdit(self.miscellaneTab)
        self.lineEdit_HorizSafeDistance.setGeometry(QtCore.QRect(440, 50, 80, 20))
        self.lineEdit_HorizSafeDistance.setObjectName("lineEdit_HorizSafeDistance")
        intVal = QtGui.QIntValidator()
        self.lineEdit_HorizSafeDistance.setValidator(intVal)
        
        
        self.lineEdit_VertSafeDistance = QtGui.QLineEdit(self.miscellaneTab)
        self.lineEdit_VertSafeDistance.setGeometry(QtCore.QRect(440, 80, 80, 20))
        self.lineEdit_VertSafeDistance.setObjectName("lineEdit_VertSafeDistance")
        intVal = QtGui.QIntValidator()
        self.lineEdit_VertSafeDistance.setValidator(intVal)
        
        self.label_H_S_D_m = QtGui.QLabel(self.miscellaneTab)
        self.label_H_S_D_m.setGeometry(QtCore.QRect(520, 50, 20, 20))
        self.label_H_S_D_m.setMinimumSize(QtCore.QSize(20, 20))
        self.label_H_S_D_m.setObjectName("label_H_S_D_m")
        self.label_V_S_D_m = QtGui.QLabel(self.miscellaneTab)
        self.label_V_S_D_m.setGeometry(QtCore.QRect(520, 80, 20, 20))
        self.label_V_S_D_m.setMinimumSize(QtCore.QSize(20, 20))
        self.label_V_S_D_m.setObjectName("label_V_S_D_m")
        self.lineEdit_SimEffectID = QtGui.QLineEdit(self.miscellaneTab)
        self.lineEdit_SimEffectID.setGeometry(QtCore.QRect(440, 110, 130, 20))
        self.lineEdit_SimEffectID.setObjectName("lineEdit_SimEffectID")
        
        
        self.lineEdit_Rating = QtGui.QLineEdit(self.miscellaneTab)
        self.lineEdit_Rating.setGeometry(QtCore.QRect(440, 140, 130, 20))
        self.lineEdit_Rating.setObjectName("lineEdit_Rating")
        
        
        self.lineEdit_information = QtGui.QLineEdit(self.miscellaneTab)
        self.lineEdit_information.setGeometry(QtCore.QRect(440, 170, 130, 20))
        self.lineEdit_information.setObjectName("lineEdit_information")
        self.label_Supplier = QtGui.QLabel(self.miscellaneTab)
        self.label_Supplier.setGeometry(QtCore.QRect(680, 20, 75, 20))
        self.label_Supplier.setMinimumSize(QtCore.QSize(75, 20))
        self.label_Supplier.setObjectName("label_Supplier")
        self.label_producer = QtGui.QLabel(self.miscellaneTab)
        self.label_producer.setGeometry(QtCore.QRect(680, 70, 75, 20))
        self.label_producer.setMinimumSize(QtCore.QSize(75, 20))
        self.label_producer.setObjectName("label_producer")
        self.label_itemNo = QtGui.QLabel(self.miscellaneTab)
        self.label_itemNo.setGeometry(QtCore.QRect(680, 120, 75, 20))
        self.label_itemNo.setMinimumSize(QtCore.QSize(75, 20))
        self.label_itemNo.setObjectName("label_itemNo")
        self.label_stockPlace = QtGui.QLabel(self.miscellaneTab)
        self.label_stockPlace.setGeometry(QtCore.QRect(680, 170, 75, 20))
        self.label_stockPlace.setMinimumSize(QtCore.QSize(75, 20))
        self.label_stockPlace.setObjectName("label_stockPlace")
        self.label_Price = QtGui.QLabel(self.miscellaneTab)
        self.label_Price.setGeometry(QtCore.QRect(680, 220, 75, 20))
        self.label_Price.setMinimumSize(QtCore.QSize(75, 20))
        self.label_Price.setObjectName("label_Price")
        self.label_calcFactor = QtGui.QLabel(self.miscellaneTab)
        self.label_calcFactor.setGeometry(QtCore.QRect(680, 270, 75, 20))
        self.label_calcFactor.setMinimumSize(QtCore.QSize(75, 20))
        self.label_calcFactor.setObjectName("label_calcFactor")
        self.lineEdit_supplier = QtGui.QLineEdit(self.miscellaneTab)
        self.lineEdit_supplier.setGeometry(QtCore.QRect(760, 20, 140, 20))
        self.lineEdit_supplier.setObjectName("lineEdit_supplier")
        self.lineEdit_producer = QtGui.QLineEdit(self.miscellaneTab)
        self.lineEdit_producer.setGeometry(QtCore.QRect(760, 70, 140, 20))
        self.lineEdit_producer.setObjectName("lineEdit_producer")
        self.lineEdit_itemNo = QtGui.QLineEdit(self.miscellaneTab)
        self.lineEdit_itemNo.setGeometry(QtCore.QRect(760, 120, 140, 20))
        self.lineEdit_itemNo.setObjectName("lineEdit_itemNo")
        self.lineEdit_StockPlace = QtGui.QLineEdit(self.miscellaneTab)
        self.lineEdit_StockPlace.setGeometry(QtCore.QRect(760, 170, 140, 20))
        self.lineEdit_StockPlace.setObjectName("lineEdit_StockPlace")
        self.lineEdit_Price = QtGui.QLineEdit(self.miscellaneTab)
        self.lineEdit_Price.setGeometry(QtCore.QRect(760, 220, 80, 20))
        self.lineEdit_Price.setObjectName("lineEdit_Price")
        doubleVal = QtGui.QDoubleValidator()
        self.lineEdit_Price.setValidator(doubleVal)
        
        self.lineEdit_calcFactor = QtGui.QLineEdit(self.miscellaneTab)
        self.lineEdit_calcFactor.setGeometry(QtCore.QRect(760, 270, 80, 20))
        self.lineEdit_calcFactor.setObjectName("lineEdit_calcFactor")
        doubleVal = QtGui.QDoubleValidator()
        self.lineEdit_calcFactor.setValidator(doubleVal)
        
        self.label_price_Euro = QtGui.QLabel(self.miscellaneTab)
        self.label_price_Euro.setGeometry(QtCore.QRect(840, 220, 30, 20))
        self.label_price_Euro.setObjectName("label_price_Euro")
        self.label_calcFactorE_G = QtGui.QLabel(self.miscellaneTab)
        self.label_calcFactorE_G.setGeometry(QtCore.QRect(840, 270, 60, 20))
        self.label_calcFactorE_G.setObjectName("label_calcFactorE_G")
        self.labelNotes = QtGui.QLabel(self.miscellaneTab)
        self.labelNotes.setGeometry(QtCore.QRect(330, 210, 105, 20))
        self.labelNotes.setMinimumSize(QtCore.QSize(105, 20))
        self.labelNotes.setObjectName("labelNotes")
        self.textEditNotes = QtGui.QTextEdit(self.miscellaneTab)
        self.textEditNotes.setGeometry(QtCore.QRect(440, 200, 180, 90))
        self.textEditNotes.setObjectName("textEditNotes")
        self.DatabaseEditTab.addTab(self.miscellaneTab, "")
        self.pushButtonSave = QtGui.QPushButton(DatabaseDialog)
        self.pushButtonSave.setGeometry(QtCore.QRect(290, 370, 100, 30))
        self.pushButtonSave.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButtonSave.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.pushButtonCancel = QtGui.QPushButton(DatabaseDialog)
        self.pushButtonCancel.setGeometry(QtCore.QRect(620, 370, 100, 30))
        self.pushButtonCancel.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButtonCancel.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButtonCancel.setObjectName("pushButtonCancel")

        self.retranslateUi(DatabaseDialog)
        self.DatabaseEditTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DatabaseDialog)

    def retranslateUi(self, DatabaseDialog):
        DatabaseDialog.setWindowTitle(QtGui.QApplication.translate("DatabaseDialog", "DatabaseEdit", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxDbEdit.setTitle(QtGui.QApplication.translate("DatabaseDialog", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelAlias.setText(QtGui.QApplication.translate("DatabaseDialog", "Alias", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelType.setText(QtGui.QApplication.translate("DatabaseDialog", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelName.setText(QtGui.QApplication.translate("DatabaseDialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.descriptLabel.setText(QtGui.QApplication.translate("DatabaseDialog", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeLabel.setText(QtGui.QApplication.translate("DatabaseDialog", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.StockLabel.setText(QtGui.QApplication.translate("DatabaseDialog", "Stock", None, QtGui.QApplication.UnicodeUTF8))
        self.mmLabel.setText(QtGui.QApplication.translate("DatabaseDialog", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_effectUsed.setText(QtGui.QApplication.translate("DatabaseDialog", "Used Effects", None, QtGui.QApplication.UnicodeUTF8))
        self.label_effectPrice.setText(QtGui.QApplication.translate("DatabaseDialog", "Piece", None, QtGui.QApplication.UnicodeUTF8))
        self.label_min.setText(QtGui.QApplication.translate("DatabaseDialog", "Min.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Best.setText(QtGui.QApplication.translate("DatabaseDialog", "Best.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_minPrice.setText(QtGui.QApplication.translate("DatabaseDialog", "Piece", None, QtGui.QApplication.UnicodeUTF8))
        self.label_bestPrice.setText(QtGui.QApplication.translate("DatabaseDialog", "Piece", None, QtGui.QApplication.UnicodeUTF8))
        self.label_riseTime.setText(QtGui.QApplication.translate("DatabaseDialog", "Rising Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_risTimeSec.setText(QtGui.QApplication.translate("DatabaseDialog", "sec", None, QtGui.QApplication.UnicodeUTF8))
        self.label_effect1.setText(QtGui.QApplication.translate("DatabaseDialog", "Effect 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_color1.setText(QtGui.QApplication.translate("DatabaseDialog", "Color 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_duration1.setText(QtGui.QApplication.translate("DatabaseDialog", "Duration 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_duration2.setText(QtGui.QApplication.translate("DatabaseDialog", "Duration 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_effect2.setText(QtGui.QApplication.translate("DatabaseDialog", "Effect 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_color2.setText(QtGui.QApplication.translate("DatabaseDialog", "Color 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_druationSeconds.setText(QtGui.QApplication.translate("DatabaseDialog", "sec", None, QtGui.QApplication.UnicodeUTF8))
        self.label_durationSeconds.setText(QtGui.QApplication.translate("DatabaseDialog", "sec", None, QtGui.QApplication.UnicodeUTF8))
        self.label_effect3.setText(QtGui.QApplication.translate("DatabaseDialog", "Effect 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_color3.setText(QtGui.QApplication.translate("DatabaseDialog", "Color 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_duration3.setText(QtGui.QApplication.translate("DatabaseDialog", "Duration 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_durationSeconds3.setText(QtGui.QApplication.translate("DatabaseDialog", "sec", None, QtGui.QApplication.UnicodeUTF8))
        self.label_shots.setText(QtGui.QApplication.translate("DatabaseDialog", "Shots", None, QtGui.QApplication.UnicodeUTF8))
        self.label_application.setText(QtGui.QApplication.translate("DatabaseDialog", "Application", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_indoor.setText(QtGui.QApplication.translate("DatabaseDialog", "Indoor", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_outdoor.setText(QtGui.QApplication.translate("DatabaseDialog", "Outdoor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_riseHeight.setText(QtGui.QApplication.translate("DatabaseDialog", "Rising height", None, QtGui.QApplication.UnicodeUTF8))
        self.label_diameter.setText(QtGui.QApplication.translate("DatabaseDialog", "Diameter", None, QtGui.QApplication.UnicodeUTF8))
        self.effectIconLabel.setText(QtGui.QApplication.translate("DatabaseDialog", "       NO PIC", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxColor1.setItemText(1, QtGui.QApplication.translate("DatabaseDialog", "White", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxColor1.setItemText(2, QtGui.QApplication.translate("DatabaseDialog", "Black", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxColor1.setItemText(3, QtGui.QApplication.translate("DatabaseDialog", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxColor1.setItemText(4, QtGui.QApplication.translate("DatabaseDialog", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxColor1.setItemText(5, QtGui.QApplication.translate("DatabaseDialog", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxColor1.setItemText(6, QtGui.QApplication.translate("DatabaseDialog", "Cyan", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxColor1.setItemText(7, QtGui.QApplication.translate("DatabaseDialog", "Magenta", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxColor1.setItemText(8, QtGui.QApplication.translate("DatabaseDialog", "Yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxColor1.setItemText(9, QtGui.QApplication.translate("DatabaseDialog", "Gray", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxColor2.setItemText(1, QtGui.QApplication.translate("DatabaseDialog", "White", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxColor2.setItemText(2, QtGui.QApplication.translate("DatabaseDialog", "Black", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxColor2.setItemText(3, QtGui.QApplication.translate("DatabaseDialog", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxColor2.setItemText(4, QtGui.QApplication.translate("DatabaseDialog", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxColor2.setItemText(5, QtGui.QApplication.translate("DatabaseDialog", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxColor2.setItemText(6, QtGui.QApplication.translate("DatabaseDialog", "Cyan", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxColor2.setItemText(7, QtGui.QApplication.translate("DatabaseDialog", "Magenta", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxColor2.setItemText(8, QtGui.QApplication.translate("DatabaseDialog", "Yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxColor2.setItemText(9, QtGui.QApplication.translate("DatabaseDialog", "Gray", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxColor3.setItemText(1, QtGui.QApplication.translate("DatabaseDialog", "White", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxColor3.setItemText(2, QtGui.QApplication.translate("DatabaseDialog", "Black", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxColor3.setItemText(3, QtGui.QApplication.translate("DatabaseDialog", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxColor3.setItemText(4, QtGui.QApplication.translate("DatabaseDialog", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxColor3.setItemText(5, QtGui.QApplication.translate("DatabaseDialog", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxColor3.setItemText(6, QtGui.QApplication.translate("DatabaseDialog", "Cyan", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxColor3.setItemText(7, QtGui.QApplication.translate("DatabaseDialog", "Magenta", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxColor3.setItemText(8, QtGui.QApplication.translate("DatabaseDialog", "Yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxColor3.setItemText(9, QtGui.QApplication.translate("DatabaseDialog", "Gray", None, QtGui.QApplication.UnicodeUTF8))
        self.label_risingHeight_m.setText(QtGui.QApplication.translate("DatabaseDialog", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_diameter_m.setText(QtGui.QApplication.translate("DatabaseDialog", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_stockPrice.setText(QtGui.QApplication.translate("DatabaseDialog", "Piece", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxType.setItemText(0, QtGui.QApplication.translate("DatabaseDialog", "coco", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxType.setItemText(1, QtGui.QApplication.translate("DatabaseDialog", "brocade", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxType.setItemText(2, QtGui.QApplication.translate("DatabaseDialog", "gorgrous", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxType.setItemText(3, QtGui.QApplication.translate("DatabaseDialog", "peony", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxType.setItemText(4, QtGui.QApplication.translate("DatabaseDialog", "candle", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxType.setItemText(5, QtGui.QApplication.translate("DatabaseDialog", "pot flower", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxType.setItemText(6, QtGui.QApplication.translate("DatabaseDialog", "willow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxType.setItemText(7, QtGui.QApplication.translate("DatabaseDialog", "glint", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxType.setItemText(8, QtGui.QApplication.translate("DatabaseDialog", "mum", None, QtGui.QApplication.UnicodeUTF8))
        self.DatabaseEditTab.setTabText(self.DatabaseEditTab.indexOf(self.effectTab), QtGui.QApplication.translate("DatabaseDialog", "Effect", None, QtGui.QApplication.UnicodeUTF8))
        self.label_UNnumber.setText(QtGui.QApplication.translate("DatabaseDialog", "UN Number", None, QtGui.QApplication.UnicodeUTF8))
        self.label_class.setText(QtGui.QApplication.translate("DatabaseDialog", "Class", None, QtGui.QApplication.UnicodeUTF8))
        self.label_chiper.setText(QtGui.QApplication.translate("DatabaseDialog", "Chipher", None, QtGui.QApplication.UnicodeUTF8))
        self.label_BAM_Number.setText(QtGui.QApplication.translate("DatabaseDialog", "BAM Number", None, QtGui.QApplication.UnicodeUTF8))
        self.label_weightNet.setText(QtGui.QApplication.translate("DatabaseDialog", "Weight Net", None, QtGui.QApplication.UnicodeUTF8))
        self.label_weightGross.setText(QtGui.QApplication.translate("DatabaseDialog", "Weight Gross", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ADRclass.setText(QtGui.QApplication.translate("DatabaseDialog", "ADR Class", None, QtGui.QApplication.UnicodeUTF8))
        self.label_weightNetKg.setText(QtGui.QApplication.translate("DatabaseDialog", "Kg", None, QtGui.QApplication.UnicodeUTF8))
        self.label_weightGrossKg.setText(QtGui.QApplication.translate("DatabaseDialog", "Kg", None, QtGui.QApplication.UnicodeUTF8))
        self.label_safeDistance.setText(QtGui.QApplication.translate("DatabaseDialog", "Safety Distance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_HorizSafeDis.setText(QtGui.QApplication.translate("DatabaseDialog", "S.D.Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_VertSafeDistance.setText(QtGui.QApplication.translate("DatabaseDialog", "S.D.Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ShowSimEffectID.setText(QtGui.QApplication.translate("DatabaseDialog", "ShowSim Effect ID", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Rating.setText(QtGui.QApplication.translate("DatabaseDialog", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.label_information.setText(QtGui.QApplication.translate("DatabaseDialog", "Information", None, QtGui.QApplication.UnicodeUTF8))
        self.label_H_S_D_m.setText(QtGui.QApplication.translate("DatabaseDialog", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_V_S_D_m.setText(QtGui.QApplication.translate("DatabaseDialog", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Supplier.setText(QtGui.QApplication.translate("DatabaseDialog", "Supplier", None, QtGui.QApplication.UnicodeUTF8))
        self.label_producer.setText(QtGui.QApplication.translate("DatabaseDialog", "Producer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_itemNo.setText(QtGui.QApplication.translate("DatabaseDialog", "Item No.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_stockPlace.setText(QtGui.QApplication.translate("DatabaseDialog", "Stock Place", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Price.setText(QtGui.QApplication.translate("DatabaseDialog", "Price", None, QtGui.QApplication.UnicodeUTF8))
        self.label_calcFactor.setText(QtGui.QApplication.translate("DatabaseDialog", "Calc.Factor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_price_Euro.setText(QtGui.QApplication.translate("DatabaseDialog", "€", None, QtGui.QApplication.UnicodeUTF8))
        self.label_calcFactorE_G.setText(QtGui.QApplication.translate("DatabaseDialog", "[E.G. 1.3]", None, QtGui.QApplication.UnicodeUTF8))
        self.labelNotes.setText(QtGui.QApplication.translate("DatabaseDialog", "Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.DatabaseEditTab.setTabText(self.DatabaseEditTab.indexOf(self.miscellaneTab), QtGui.QApplication.translate("DatabaseDialog", "Miscellaneous", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSave.setText(QtGui.QApplication.translate("DatabaseDialog", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCancel.setText(QtGui.QApplication.translate("DatabaseDialog", "Cancle", None, QtGui.QApplication.UnicodeUTF8))

